### ISSUE TITLE
Add support for OracleDB monitoring

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics#104]
I'd like to add support for the oracledb npm module.

The data produced would be:
# Event: 'oracledb'

Emitted when an OracleDB 'execute' method is called

* `data` (Object) the data from the OracleDB event:
 * `time` (Number) the time in milliseconds when the OracleDB event occurred. This can be converted to a Date using new Date(data.time)
 * `query` (String) the query that was executed
 * `duration` (Number) the time taken in milliseconds.

**Comment by sjanuary** [comment]
I've implemented this on my oracledb branch - https://github.com/sjanuary/appmetrics/blob/oracledb/probes/oracledb-probe.js

Could anyone review it please?

**Comment by hhellyeribm** [comment]
Looks fine, please create a merge-able pull request and I'll accept it.

**Comment by sjanuary** [comment]
Thanks @hhellyeribm
