### ISSUE TITLE
Add support for Node v5

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#109]
Compile from source appears to be working, but more testing would be good.
Pre-compiled binaries for the npmjs.org install will be needed.

**Comment by xiaoshimimi** [comment]
Do you have plan to deliver the support in appmetrics 1.0.4? or We must wait for 1.0.5? Because with the agent formal install process, we cannot get appmetrics from github.com. We need your schedule to plan our test method.

**Comment by tunniclm** [comment]
1.0.4 has already gone, so this would have to be for a later release.

The project doesn't appear to require any modification, nevertheless there is a small amount of work required to update the install scripts, and set up the build and packaging jobs.

**Comment by xiaoshimimi** [comment]
I tried to install 1.0.5 with Node.js 5.2.0, with npm install appmetrics, and npm install git://github.com/RuntimeTools, both failed. 

So we decide to drop v5 support for 8.1.3 release.

**Comment by tobespc** [comment]
the next release of appmetrics - 1.0.8 is going to have node 5 support built in

**Comment by tobespc** [comment]
5 support is now included in 1.0.8
