### ISSUE TITLE
Add support for elasticsearch probe

### ISSUE THREAD

**Issue by tobalsgithub** [RuntimeTools/appmetrics#112]
Thoughts on creating an elasticsearch probe? Not sure exactly how that would work since it's just an http request, but would be nice to see.

**Comment by seabaylea** [comment]
There shouldn't be any reason why we can't collect data from the Elasticsearch client APIs. Is there any information in particular that's you'd be interested in?

**Comment by tobalsgithub** [comment]
Mostly interested in the request time, from request initiated to response received. But adding the query information would be nice. I'm thinking about the postgres and mysql probes and thinking having something like that for elasticsearch would be really nice.

**Comment by seabaylea** [comment]
@tobalsgithub Adding monitoring for APIs like `client.search()` should be pretty straightforward. The challenge is in knowing what context data to provide.

The `index` could be added pretty easily if its interesting. Things like the query could become more complicated though - the simple string query (a `q` field) would be easy to add, but where the query is a more complex object its harder to know what to grab from the the set of query options and config parameters.

Any guidance on what data you'd need would be really useful.

**Comment by tobalsgithub** [comment]
I'm thinking we could start with just the indices and document types and see how far that gets us. Most of our queries are more complicated than the simple `q` field, and that's what I've seen out in the while as well.

Would that work?

**Comment by sjanuary** [comment]
No plans to do this in the near future so I'm adding the ice box label, although we're open to PRs if someone else is interested in doing the work.
