### ISSUE TITLE
Document how to build appmetrics

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#12]
This should include building from a clone of the github repository and installing directly from github with npm.

**Summary**
_Clone from github_

```
git clone https://github.com/RuntimeTools/appmetrics
```

You now have latest dev code. To change to the latest release:

```
git checkout latest-release
```

To build inside the source tree (without downloading Health Center core binaries):

```
npm install node-gyp nan@1.8.4
node_modules/.bin/node-gyp configure rebuild
```

To build and install (and run install scripts), go up a level and install the project directory:

```
cd ..
npm install ./appmetrics
```

_Install direct from github_
Latest release: `npm install git+https://github.com/RuntimeTools/appmetrics#latest-release`
Latest dev: `npm install git+https://github.com/RuntimeTools/appmetrics`

**Comment by tunniclm** [comment]
Document should include information on compiler restrictions for Windows. The Health Center core agent library is built with v120 of the MSVS runtime library, and the Node Application Metrics needs to compiled against matching libraries (Visual Studio 2013).

**Comment by mattcolegate** [comment]
@tunniclm I think this has now been documented under the following Wiki pages:
https://github.com/RuntimeTools/appmetrics/wiki/Developing
https://github.com/RuntimeTools/appmetrics/wiki/Install-direct-from-github-source
https://github.com/RuntimeTools/appmetrics/wiki/Prerequisites-for-building-appmetrics-from-source-code

They can be found from the README:
"Source code

The source code for Node Application Metrics is available in the appmetrics project. Information on working with the source code -- installing from source, developing, contributing -- is available on the appmetrics wiki."

If you agree that this documentation covers this issue, please close the issue.

**Comment by tunniclm** [comment]
@mattcolegate I think it bears going through--that is, an attempt to build appmetrics only by following the verbatim instructions in the wiki pages, to make sure that there's nothing that we're inadvertently missing. Provided that is satisfactory, then I think this issue is complete.

**Comment by mattcolegate** [comment]
Good call - it fails to build with the current instructions! I'll update them and test on both Windows and Linux. It's going to involve an update to binding.gyp too.

**Comment by sjanuary** [comment]
Updated instructions in the Wiki
