### ISSUE TITLE
Document development process for appmetrics

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#13]
This should describe the use of branches, tags and milestones/versions in the package.json and any license files.

**Comment by mattcolegate** [comment]
I think this is covered in https://github.com/RuntimeTools/appmetrics/wiki/Developing. If you agree, please close the issue.

**Comment by tunniclm** [comment]
I think the wiki page could do with a bit more description of the generate flow/decision process of developing and releasing code, particularly with a view to encouraging engagement and contributions.

**Comment by sjanuary** [comment]
Probably not going to do any more on this for now unless anyone wants to provide a PR, or we get a lot of people asking for it.  Adding the ice box label.
