### ISSUE TITLE
Add support for StrongOracle monitoring

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics#134]
I recently added support for monitioring the OracleDB database client #104. StrongOracle is also a popular client for Oracle databases, so I'd like to add support for monitoring StrongOracle too.

The data produced will be:
# Event: 'strong-oracle'

Emitted when an StrongOracle 'execute' method is called

* `data` (Object) the data from the strong-oracle event:
 * `time` (Number) the time in milliseconds when the event occurred. This can be converted to a Date using new Date(data.time)
 * `query` (String) the query that was executed
 * `duration` (Number) the time taken in milliseconds.

**Comment by sjanuary** [comment]
I've implemented this probe in my personal branch if anyone has time to review?

https://github.com/sjanuary/appmetrics/commit/705d6c2b783f69d45862398e5e4552657f7d0cf4

Also I think this issue should have an 'enhancement' label but I can't see how to add it, maybe because I'm not an admin?

**Comment by hhellyeribm** [comment]
Code looks good, though I haven't installed Oracle to test it.
I've added the enhancement tag.

**Comment by sjanuary** [comment]
Thank you, I've created a pull request.

**Comment by sjanuary** [comment]
Now merged, thanks @hhellyer
