### ISSUE TITLE
Mongoose and appmetrics

### ISSUE THREAD

**Issue by muhamed-didovic** [RuntimeTools/appmetrics#152]
Hi,

I have question regarding mongo, is it possible to track 'stats' related to mongodb with app metrics if you use  mongoose. I see in docs that I need mongodb package.
Did anyone has same request?

**Comment by sjanuary** [comment]
Appmetrics doesn't currently have a probe for mongoose itself, although if mongoose uses the mongodb module you should get mongodb information out.  Have you tried it out?

**Comment by tobespc** [comment]
@muhamed-didovic Have you been able to get the information you needed from the the mongodb data ?

**Comment by parwat08** [comment]
@sjanuary @tobespc 
var mongo = require('mongoose');

monitoring.on('mongo', function(data) {
    console.log('mongoose data', data);
});

it won't print anything

**Comment by sjanuary** [comment]
I've just investigated this and appmetrics definitely doesn't work with Mongoose, even with the updates in PR #426 to support the latest MongoDB API.  This is either because of the specific way we need require statements to be written, or because Mongoose itself wraps the MongoDB Collection, which may mean that our injected code doesn't get called.

We're open to PRs if anyone is interested in adding Mongoose support, but I'll close this issue for now since it's not something we're planning to do in the near future.

**Comment by lardissone** [comment]
I've found a workaround for this, do the .enable('mongo') after the mongoose connections is done:

    const mongoose = require('mongoose')
    const appmetrics = require('appmetrics')

    mongoose.createConnection(config.mongodb.uri, config.mongodb.options)
    .on('connected', function () {
        appmetrics.enable('mongo')
        debug('connected')
    })

Probably this also works for #151 but haven't tried.

**Comment by sebastianarena** [comment]
A little late to the party. But I finally have `mongoose` working properly with `appmetrics`.
DISCLAIMER: @lardissone and I work together, so I continued upon his work.

1) `appmetrics.enable('mongo')` needs to actually be `appmetrics.enable('mongodb')`
2) `appmetrics` needs to be required before mongo/mongoose in order for it to hook up correctly. In fact, we created our own appmetrics controller to enable whatever we need, and is now the FIRST line in our node app. That alone made a huge difference, and now we get everything from mongo, and other services as well.

**Comment by gustavomassa** [comment]
@sebastianarena 

I'm not able to enable/use the mongo/mongodb metrics. I'm using the mongodb native driver.
The require of appmetrics is the first thing on the Main file, I'm using node cluster module.
All the other metrics are working fine for both master and all workers.

```
    public init(): void {
        try {
            this.appmetrics.configure(
                {
                    applicationID: this.applicationID,
                    mqtt: 'off',
                    profiling: 'off'
                }
            );

            this.appmetrics.start();
            this.monitoring = this.appmetrics.monitor();
            this.registerAppMetricsEvents();

        } catch (ex) {
            Webbuffet.logError(ex.message, ex);
        }
    }

            private registerAppMetricsEvents(): void {
        if (!this.appmetrics || !this.monitoring) throw new Error('appmetrics/monitoring is NULL');

        try {
            this.monitoring.on('initialized', (env) => {
                Webbuffet.log(`Service ${config.name} initialized appmetrics monitoring on ${(isWorker) ? worker['name'] : 'master'} process`);
                
                this.appmetrics.enable('mongo');
                this.appmetrics.enable('mongodb');

                this.monitoring.enable('mongo');
                this.monitoring.enable('mongodb');
            });

            //every cpu sample taken
            this.monitoring.on('cpu', (cpu) => {
                Webbuffet.sendTelemetry('cpu', cpu);
            });

            //every memory sample taken
            this.monitoring.on('memory', (memory) => {
                Webbuffet.sendTelemetry('memory', memory);
            });

            //every 5 seconds
            this.monitoring.on('eventloop', (eventLoop) => {
                Webbuffet.sendTelemetry('eventloop', eventLoop);
            });

            this.monitoring.on('mongo', (mongo) => {
                Webbuffet.sendTelemetry('mongo', mongo);
            });

            this.monitoring.on('mongodb', (mongodb) => {
                Webbuffet.sendTelemetry('mongodb', mongodb);
            });

        } catch (ex) {
            throw ex;
        }
    }

```

**Comment by sebastianarena** [comment]
@gustavomassa Yep, it's hard. appmetrics works great... when you get to see it running. Mongo is certainly one of the trickiest ones. It took us days to figure out. Nothing I can say will make your configuration working... the real truth is that any sort of connection to external resources like MongoDb needs to happen after you require appmetrics and enable it. Period. If you do that, you might get lucky and get it running. Hope you figure out!
