### ISSUE TITLE
Acme-air v2 application crash in 2 days without any memory leak 

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#156]
We test with : [https://github.com/acmeair/acmeair-nodejs application](https://github.com/acmeair/acmeair-nodejs application) + ibm-apm + appmetrics, with a 25000 req/min throughput, the application will be crash without any memory leak.

**Comment by tobespc** [comment]
will track in email

**Comment by tobespc** [comment]
this was fixed under issue #164
