### ISSUE TITLE
Appmetrics 1.0.7 fails to install from github

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#159]
When installing from github we see the following error during install:
```shell
Failed to gunzip: unexpected end of file
```

When trying to use appmetrics we see this error:
```shell
Failed to open library /home/tunniclm/Projects/appmetricstst/node_modules/appmetrics/libagentcore.so:/home/tunniclm/Projects/appmetricstst/node_modules/appmetrics/libagentcore.so: cannot open shared object file: No such file or directory
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Failed to initialize Agent Core library
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/tunniclm/Projects/appmetricstst/node_modules/appmetrics/index.js:25:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

This problem is introduced by PR #137 for issue #136 which changed the way files are downloaded to use the `request` package instead of http. This was intended to enable downloads from behind a proxy, however, the implementation was not correct and from that point on downloads would not work.

This only affected appmetrics installs from github (and not npm) since the `download_all_binaries.js` used in the npm package was not updated by #137 and still used the old download code.

**Comment by tunniclm** [comment]
Attached PR should fix `download_licenses.js` and `download_binaries.js`.
The `download_all_binaries.js` script used in the npm package should also be updated.

**Comment by tunniclm** [comment]
To clarify what PR #137 did incorrectly: it used `request(url, function(err, response, body) {...})` and then tried to create a pipe from the `request` object.

However, this use of `request()` downloads the whole content of the download stream into the `body` variable, leaving the stream (which is part of the `response` object) empty. Therefore the pipe fails on the first read with "unexpected end of file".

The change in #160 changes the `request()` call to use the `request(url)` form which allows streaming via a call to `pipe()`.

**Comment by hhellyer** [comment]
Thanks Mike, that makes sense of apparent refactoring fixing the problem - it's more than that it's using a different mechanism (despite being the same function name).
