### ISSUE TITLE
install scripts unreliable

### ISSUE THREAD

**Issue by rmg** [RuntimeTools/appmetrics#169]
The download scripts that are run from the `install` script in package.json make use of modules that are dependencies. Despite what the names suggest, the dependencies aren't actually guaranteed to be installed before `preinstall`, `install`, or `postinstall` are run - unless the user is running npm v3+.

The fact that this hasn't been a problem yet is mostly a matter of luck.

The general solutions that aren't simply "don't do it" are:
 - bundle the dependencies that are used by the scripts
 - rewrite the scripts to only rely on node core
 - ask people to upgrade to npm 3 if/when they report weird bugs about `tar` or `graceful-fs` not being found during install

**Comment by sjanuary** [comment]
I think this is fixed by #289
