### ISSUE TITLE
Include Binaries

### ISSUE THREAD

**Issue by robertschultz** [RuntimeTools/appmetrics#171]
For those of us who want to have a locked down CI/CD system, the method you guys have today doesn't work. We don't authorize our build agents to access outside of the firewall. All modules go through a proxy (artifactory), so the script you have to fetch the binaries doesn't work.

My option is to fork your module, add them in and rebuild it and host it internally to keep things clean.

Can you ship the binaries somehow which each release of the npm module itself?

**Comment by tobespc** [comment]
This is something we are looking at resolving and ultimately, we will end up without the need to require those binaries at all.  However, for the current implementation they are still required.  I'll look at whether we can modify our packaging to prevent the fetching of the binaries

**Comment by seabaylea** [comment]
The challenge with including all the binaries is the additional size the package becomes. To support the matrix of all OS/architecture combinations and major Node.js versions would increase the package size to ~12MB today, and that would increase with new versions of Node.js (major and minor) are supported.

Ultimately, as @tobespc says, we know we need to remove the binary dependency - and the way to do that is to provide the source so those binaries can be compiled on install.

I know Artifactory can host packages of many types. As a (hopefully very) short term solution is there scope to host the binaries in Artifactory, and for us to provide a mechanism to pull from the Artifactory instance?

**Comment by sam-github** [comment]
node-pre-gyp has a reasonable approach, it tries to fetch, if it fails, it tries to build, if that fails... it fails.

**Comment by tobespc** [comment]
the next release of appemetrics - 1.0.12 will package all binaries together on npm removing the need to have firewalls opened for other host sites
