### ISSUE TITLE
Add support for Http Status

### ISSUE THREAD

**Issue by saxis** [RuntimeTools/appmetrics#172]
Would be helpful to get the http responses as part of the http monitor.

**Comment by tobespc** [comment]
@saxis Yes, we can add that, I'll put a change together this week

**Comment by tobespc** [comment]
@saxis Are you just after the status code or are are there any other fields you be interested in?

**Comment by saxis** [comment]
Content-type, the header itself also if possible.

**Comment by tobespc** [comment]
@saxis does this change meet your requirements if you now pull a build from git ?

**Comment by tobespc** [comment]
@saxis have you have had a chance to run tests with the updated http response data ?   I'll add it to the next release if it meets your requirements

**Comment by saxis** [comment]
Sorry for the delayed response. Yes our needs are met, thanks very much.
