### ISSUE TITLE
Support HTTP calls

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics#180]
There is already an HTTP type, but it refers to HTTP calls to the application itself. I'd like the ability to monitor HTTP calls _from_ the application. So for example, imagine my application makes use of Watson APIs. I'd like to monitor the calls from my app to the remote API including seeing the URL as well as the duration.

**Comment by tobespc** [comment]
@cfjedimaster This is now implemented in issue #365
