### ISSUE TITLE
Bus issues

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics#182]
When using Node 5, which I know isn't officially supported, I get random bus errors while using app metrics.

**Comment by hhellyer** [comment]
Support for Node 5 is covered by issue #109.
I'm not sure if we'd expect to see a crash or not. What platform / OS are you running on?

**Comment by cfjedimaster** [comment]
OSX.

**Comment by hhellyer** [comment]
I've managed to reproduce the crash with Node 5, on Mac OSX with appmetrics installed from the master branch on github. I enabled core dumps and this is the stack trace:

```
(lldb) bt
* thread #1: tid = 0x0000, 0x0000000100f0a018 node`default_loop_struct + 584, stop reason = signal SIGSTOP
  * frame #0: 0x0000000100f0a018 node`default_loop_struct + 584
    frame #1: 0x00000001007803ad node`uv__async_event + 198
    frame #2: 0x0000000100780540 node`uv__async_io + 136
    frame #3: 0x000000010078f232 node`uv__io_poll + 1554
    frame #4: 0x00000001007809f3 node`uv_run + 321
    frame #5: 0x000000010065a315 node`node::Start(int, char**) + 594
    frame #6: 0x0000000100001434 node`start + 52
```

It matches a crash we've been seeing very intermittently on Node 4 on Linux. That's tracked under issue #174 but has been very hard to reproduce. I have a (possible) fix which I’ve now been able to stress test against Node 5 to see if I can validate the fix locally. That seems to show it’s working (I’m getting the crash around 4/10 runs without my change and so haven’t seen it with the fix) so I’ve pushed the branch up.

I’ll raise a pull request but in the meantime you could try my fix by doing:
npm install hhellyer/appmetrics#async_init_fix
if you are able to install from github and see if that resolves the issue for you.
(I am assuming you are currently installing from the [Runtimetools/appmetrics](https://github.com/RuntimeTools/appmetrics) master branch on github)

**Comment by cfjedimaster** [comment]
I think this did it. I've had it running for 20ish minutes with no problem. Thank you. :)

**Comment by tobespc** [comment]
Can this be closed now ?

**Comment by cfjedimaster** [comment]
I'd say so.

**Comment by hhellyer** [comment]
Closing as fixed.
