### ISSUE TITLE
Cannot run globally install node module

### ISSUE THREAD

**Issue by tungxfung** [RuntimeTools/appmetrics#194]

**Comment by tungxfung** [comment]
For example: 
I installed cloudcmd by "npm -g install cloudcmd"
and I cannot use node-hc to run cloudcmd

**Comment by tobespc** [comment]
Hi, the problem you have is that when you install cloudcmd globally, it creates a launcher script "cloudcmd.cmd" and its this that runs when you type "cloudcmd" from the console.  If you edit that file (mine was in c:\users\admin\AppData\Roaming\npm") and change the line that says 

node  "%~dp0\node_modules\cloudcmd\bin\cloudcmd.js" %*

to be 

node-hc  "%~dp0\node_modules\cloudcmd\bin\cloudcmd.js" %*

You will then get appmetrics loaded when you run
