### ISSUE TITLE
disable mqtt

### ISSUE THREAD

**Issue by majgis** [RuntimeTools/appmetrics#209]
This log message appears despite configuration:
```
[Wed May  4 09:58:44 2016] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
```

Configuration:
```
com.ibm.diagnostics.healthcenter.mqtt=off
```

Am I wrong in assuming that this configuration should result in no attempt to connect to the broker?  Is there another configuration I should be using if I only want to use the API?

**Comment by tobespc** [comment]
at the moment, appmetrics is hardcoded to always attempt an mqtt connection.  We will be updating this shortly to adhere to the setting in the properties file

**Comment by majgis** [comment]
https://github.com/RuntimeTools/appmetrics/blob/8bbe47aaecd9499f17e1a996d3db6f13b6bfa284/src/appmetrics.cpp#L291

Ok, thanks.
