### ISSUE TITLE
Windows builds are gone for Node.js 5

### ISSUE THREAD

**Issue by agdevbridge** [RuntimeTools/appmetrics#212]
I can install this module using Node.js v5

> ERROR: Failed to download http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/runtimes/tools/healthcenter/agents/nodejs/tgz/5/appmetrics-1.0.9-win32-x64.tgz: HTTP 404

There are no windows builds in:
http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/runtimes/tools/healthcenter/agents/nodejs/tgz/5/

**Comment by tobespc** [comment]
umm, ok, investigating that now for you

**Comment by tobespc** [comment]
@agdevbridge You are correct, we do not have any windows builds avaiilable for Node.js v5 support.  We will get this fixed as soon as we can and an update pushed out with the fixed windows builds in.

**Comment by tobespc** [comment]
We do have them available for Node.js v6 though :-)

**Comment by agdevbridge** [comment]
@tobespc thanks for information, looking forward to v5 builds, because some dependencies of my app have issues with v6

**Comment by DanCunnington** [comment]
Hi @agdevbridge - Node v5 windows binaries are now available, if you run `npm install appmetrics` again it should now work. Closing this issue, feel free to re open if you have problems. Thanks
