### ISSUE TITLE
Code/Version mismatch on NPM

### ISSUE THREAD

**Issue by 0x1mason** [RuntimeTools/appmetrics#217]
If you pull `https://registry.npmjs.org/appmetrics/-/appmetrics-1.0.11.tgz` and compare `package.json` to the archive on the releases page, you'll see the `install` script lines mismatch. Is that by design?

**Comment by tobespc** [comment]
Hi, yes that is by design.  Appmetrics requires 2 binary packages when you install from npm registry but only one if you install from git (as you are building one yourself).  When we build the npm registry package, we put a different download_all_binaries.js file in the package to get both binaries
