### ISSUE TITLE
Environment plugin does not differentiate between Node.js and io.js

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#22]
The environment plugin (`src/plugins/node/env/nodeenvplugin.cpp`) message uses the field  `runtime.name` to report the variation of the SDK being monitored. 

It currently reports either:

1. `IBM SDK for Node.js` if monitoring the IBM SDK for Node.js
2. `Node.js` otherwise

Ideally it should report `io.js` if monitoring io.js.

**Comment by mattcolegate** [comment]
@tunniclm, Given io.js is not very alive anymore, can we close this item?

**Comment by tunniclm** [comment]
@mattcolegate This is really a historical thing now and I don't think many people are using io.js since the merge back into node.js. I think it makes sense to close this, we can always reopen if someone wants this.
