### ISSUE TITLE
express probe is not providing data when express.Router() method is used

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics#268]
acmeair uses express.Router() and the express probe needs to cater for this to work

**Comment by jhondavila** [comment]
the same thing happens , some correcion for this problem.
try a hook but I did not work well

**Comment by bhashah** [comment]
Hi,

If I use 'app.get(path, callback)' method for creating route paths, the express probe gets properly created and works just fine. But, in our application code, we are using 'app.route(path).all(callback).get(callback)' method to setup our express route paths. Appmetrics is not able to place express probes on routes created this way. Have you provided any solution yet to setup probes for app.route ?

**Comment by tobespc** [comment]
closing as we have removed the express probe #390 #404
