### ISSUE TITLE
upgrade to node-gyp@3.x

### ISSUE THREAD

**Issue by sam-github** [RuntimeTools/appmetrics#275]
I'd PR a change for this, but I'm not sure how to test.

Despite that it jumps a major, I suspect that it does not introduce a compatibility problem for appmetrics (and anyhow, the use of graceful-fs@3 that node-gyp@2 pulls in is going to break real soon know in node).

The change that caused the node-gyp major to bump is https://github.com/nodejs/node-gyp/pull/708, FYI, which is why I don't think its going to be a problem.

**Comment by sam-github** [comment]
Actually, there is no need for appmetrics to depend on node-gyp, its builtin to node. I suggest deleting both these lines:

- https://github.com/RuntimeTools/appmetrics/blob/master/package.json#L23
- https://github.com/RuntimeTools/appmetrics/blob/master/package.json#L18

**Comment by sjanuary** [comment]
I think we've got a separate PR for removing the node-gyp dependency so I'm going to close this now

**Comment by NikCanvin** [comment]
separate PR for removing the node-gyp dependency   https://github.com/RuntimeTools/appmetrics/pull/288
