### ISSUE TITLE
Support for BSDs

### ISSUE THREAD

**Issue by No9** [RuntimeTools/appmetrics#282]
I tried to install this on my FreeBSD environment and I received the error: 
`freebsd-x64 is not currently a supported platform`
Would be love to see this platform supported - is there anything I can do to help?

**Comment by tobespc** [comment]
@No9  have you tried installing from git ?  We package prebuilt binaries on the npm install and don't support freebsd currently but it should install and build for you if you install from this repo

**Comment by No9** [comment]
@tobespc Thanks I will give that a look

**Comment by No9** [comment]
@tobespc Just an update - looks like https://github.com/RuntimeTools/omr-agentcore needs a port implemented for BSD https://github.com/RuntimeTools/omr-agentcore/tree/master/src/ibmras/common/port

**Comment by marcotuna** [comment]
I am trying to install on FreeBSD also and I have the same issue.
omr-agentcore seems to be incompatible

**Comment by sjanuary** [comment]
We don't have any plans to add this in the near future (and don't actually have any machines with BSD installed on them) so I'm adding the ice box label, although we are open to PRs if anyone is interested in doing the work.
