### ISSUE TITLE
npm test is failing for latest code with module not found error

### ISSUE THREAD

**Issue by meghalidhoble** [RuntimeTools/appmetrics#284]
Platform details: x86 Ubuntu 16.04
Appmetrics : building from source (master) 

Steps Followed: 
1) git clone source
2) npm install inside the directory (succeeds no errors) 
3) npm test - fails for multiple tests with similar tests 
```
module.js:327
    throw err;
    ^
Error: Cannot find module "./appmetrics"
.....
module.js:327
    throw err;
    ^
Error: Cannot find module 'commander'
```
Can someone help me understand the issue here? Am I missing out on something here? 
This build was passing for me a month back? Is there any change in the way to build it?

**Comment by sjanuary** [comment]
This works for me on the latest source, but you need to do:

git clone --recursive

in order to get the omr-agentcore sub module.  Would you mind re-trying?

**Comment by meghalidhoble** [comment]
Thanks @sjanuary for the response! 
The --recursive option did helped and the its building fine now for me. We can close on this issue.
Thanks,
Meghali
