### ISSUE TITLE
memory numbers from app metrics.

### ISSUE THREAD

**Issue by D0LLAR** [RuntimeTools/appmetrics#294]
Numbers I'm seeing back from using app metrics dont  resemble those from either nmon,BM own memory monitoring  nor against internal monitoring of the processes own heap..

var heapTotalMB = process.memoryUsage().heapTotal / 1048576;
  var heapUsedMB = process.memoryUsage().heapUsed / 1048576;
file grab attached of what Im see with appmetrics from the eclipse side..
 similar timed logging using the process.memoryUsage()  from inside the node app below

{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"msg":"running in the heap monitor","time":"2016-09-14T14:51:53.044Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":139},"v":0}
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":194.8828125,"heapTotalMB":86.79403686523438,"heapUsedMB":78.61526489257812,"heapIncreased":true,"iterator":0,"previousRSSLength":0,"date":1473864781508,"msg":"monitorMemory","time":"2016-09-14T14:53:01.509Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}
1st minute here....
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":195.13671875,"heapTotalMB":86.79403686523438,"heapUsedMB":78.72457122802734,"heapIncreased":false,"iterator":0,"previousRSSLength":1,"date":1473864811514,"msg":"monitorMemory","time":"2016-09-14T14:53:31.515Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}

{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":195.80078125,"heapTotalMB":86.79403686523438,"heapUsedMB":79.82312774658203,"heapIncreased":false,"iterator":0,"previousRSSLength":1,"date":1473864841521,"msg":"monitorMemory","time":"2016-09-14T14:54:01.521Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":223.51171875,"heapTotalMB":116.27914428710938,"heapUsedMB":99.37559509277344,"heapIncreased":true,"iterator":1,"previousRSSLength":1,"date":1473864871522,"msg":"monitorMemory","time":"2016-09-14T14:54:31.522Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":261.1015625,"heapTotalMB":152.69198608398438,"heapUsedMB":126.28837585449219,"heapIncreased":true,"iterator":2,"previousRSSLength":2,"date":1473864901524,"msg":"monitorMemory","time":"2016-09-14T14:55:01.524Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":273.04296875,"heapTotalMB":165.47421264648438,"heapUsedMB":111.3638687133789,"heapIncreased":true,"iterator":3,"previousRSSLength":3,"date":1473864931528,"msg":"monitorMemory","time":"2016-09-14T14:55:31.528Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":244.68359375,"heapTotalMB":136.01913452148438,"heapUsedMB":91.69914245605469,"heapIncreased":false,"iterator":2,"previousRSSLength":4,"date":1473864961532,"msg":"monitorMemory","time":"2016-09-14T14:56:01.533Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}
{"name":"tispAPI","hostname":"b522c5a9c7f9","pid":81,"level":30,"rssMB":267.71875,"heapTotalMB":159.62680053710938,"heapUsedMB":116.27596282958984,"heapIncreased":true,"iterator":1,"previousRSSLength":1,"date":1473864991536,"msg":"monitorMemory","time":"2016-09-14T14:56:31.536Z","src":{"file":"/root/api/lib/heapmonitoring_tis_perf.js","line":124,"func":"monitorMemory"},"v":0}

![screenhunter_46 sep 15 14 19](https://cloud.githubusercontent.com/assets/7533016/18678899/79780a2e-7f55-11e6-954e-87a1c3139a10.gif)

**Comment by tobespc** [comment]
@D0LLAR We will take a look and send an update later

**Comment by stalleyj** [comment]
@D0LLAR I've taken a look at the figures appmetrics produces for 'Used heap' and they seem to match what process.memoryUsage().heapUsed gives and the verbose garbage collection information.  Could you let us know what platform you are on and what version of Node you are using please

**Comment by stalleyj** [comment]
@D0LLAR I've looked at the information you provided and the Used heap numbers from Appmetrics match those seen in GCMV from loading the verbose log.  The Used heap figures are between 4 and 6 MB through the run. Can you try a different node version to see if the problem lies there ?

**Comment by tobespc** [comment]
@D0LLAR Have you been able to recreate on a different version of Node ?

**Comment by tobespc** [comment]
@D0LLAR Is this still an issue ?  I will look to close this off shortly if its no longer a problem for you

**Comment by D0LLAR** [comment]
Not blocked by this anymore.
