### ISSUE TITLE
appmetrics removes its own files during install

### ISSUE THREAD

**Issue by sam-github** [RuntimeTools/appmetrics#300]
The intention was probably to save disk space, but the side effect is that once appmetrics is installed, it can't be reinstalled: `npm rebuild` fails.

This is made worth because npm2 under some conditions appears to install modules *twice* even though they only appear once on disk. We see this in CI on Windows boxes mostly. This wouldn't be such a big issue, except the second time the install script runs it fails, the install tgzs were all deleted after the first install.

**Comment by rmg** [comment]
I'm not able to find the troublesome install scripts in this repo to attempt a fix.. am I missing something?

**Comment by sam-github** [comment]
The script isn't in this repo, the actual packaging is closely tied to the
multi-platform build system, which aggregates the binaries from all the
platforms. I think the script should be moved here, though.
​

**Comment by sjanuary** [comment]
https://github.com/RuntimeTools/appmetrics/pull/303

**Comment by tobespc** [comment]
Closing as fixed in #300

**Comment by sjanuary** [comment]
Build system is now using this version, changes will go into 1.1.1
