### ISSUE TITLE
Should be possible to switch off connecting to MQTT broker

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics#305]
Not every user will want appmetrics to automatically connect to an MQTT broker on the default port and start sending data. E.g. they may be running an MQTT broker for something else. It should be possible to disable this.

**Comment by tobespc** [comment]
We have it on by default and never check the property

**Comment by sjanuary** [comment]
Ok, so there's already a `com.ibm.diagnostics.healthcenter.mqtt` property that you can set to off, but appmetrics doesn't actually honour it at the moment.
