### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by betweenbrain** [RuntimeTools/appmetrics#315]
Attempting to install via:
* `npm install appmetrics` results in _Refusing to install appmetrics as a dependency of itself_
* `npm install git://github.com/RuntimeTools/appmetrics#latest-release` results in _Cloning into bare repository ... fatal: read error: Operation timed out_
* downloading latest release and installing via `npm install appmetrics-1.1.1.tar.gz` results in _Tell the author that this fails on your system: node-gyp rebuild_

This is with Node.js v4.4.1 and v5.8.0

**Comment by tobespc** [comment]
@betweenbrain What platform and OS are you installing into ?

**Comment by sjanuary** [comment]
@betweenbrain - the first error comes from npm - perhaps you created a directory called appmetrics and you have run npm init and accepted the defaults, or your working directory already contains the appmetrics source?  The third error is probably a result of the same issue.

E.g. see [npm-refusing-to-install-package-as-a-dependency-of-itself](http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/) or google "npm refusing to install as a dependency of itself".

**Comment by betweenbrain** [comment]
@tobespc thanks for the quick reply. This is happening with OS X 10.10.5. Do you need any other system specifics?

**Comment by betweenbrain** [comment]
@sjanuary Thank you! That is exactly the issue. The name of the project, in `package.json`, was _appmetrics_ as this was just a small test of the module. I've never seen that before, but it's good know. 

I appreciate everyone's help and work on this module.
