### ISSUE TITLE
Checksum failure

### ISSUE THREAD

**Issue by jamesseanwright** [RuntimeTools/appmetrics#319]
Hey there,

I'm receiving a checksum mismatch when installing appmetrics. This occurs with both 1.1.0 and 1.1.2:

11:40:21 npm ERR! Expected: e48f9c9404025477e7ee3c6060edcfa86b6b8cb7
11:40:21 npm ERR! Actual:   2ae9f04d025393865ce1c31e98fde705d0934c1c

AFAIK, npm generates these SHA-1 hashes based upon the generated tarball upon publishing, but interestingly I can't reproduce this with any other module. Is my understanding of the checksum mechanism correct?

Thanks,
James

**Comment by sam-github** [comment]
can you do `npm cache clear`, and try again? sometimes npm tarballs get damaged on download, and checksum mismatches occur.

**Comment by jamesseanwright** [comment]
Sure, I'll try tomorrow and let you know!

**Comment by jamesseanwright** [comment]
Hi,

We've tried this to no avail.

Cheers,
James

**Comment by jamesseanwright** [comment]
Works like a charm. Thanks! :)
