### ISSUE TITLE
Make nodereport and heapdump available via Appmetrics API call

### ISSUE THREAD

**Issue by mattcolegate** [RuntimeTools/appmetrics#320]
NodeReport: https://github.com/nodejs/nodereport
heapdump: https://github.com/bnoordhuis/node-heapdump

Functions to expose:
require('nodereport').triggerReport()
require('heapdump').writeSnapshot()

**Comment by mattcolegate** [comment]
Will need to include these packages in dependencies and buildDependencies, then make them available from appmetrics. I'll reuse the function names for clarity.

**Comment by sam-github** [comment]
I think we need more functions for nodereport, we also need to configure the conditions under which it auto-dumps (uncaught exception, signal, etc.)

How about just exposing `appmetrics.nodereport`, so we can call anything we want on nodereport? And perhaps the same with heapdump?

**Comment by mattcolegate** [comment]
I'm confused as to what value we're adding now - it seems like we're just adding the word 'appmetrics' to the front of things. What is the benefit to the end user of this work? Surely they can just require nodereport and heapdump themselves?

**Comment by sam-github** [comment]
@mattcolegate the value is in having them pre-compiled and distributed as binaries, see https://ci.nodejs.org/job/node-test-pull-request/4806/

Compiling native addons requires:

1. network access to download the node headers (only for the first build, but still a blocker on customer sites)
2. a correctly installed compiler toolchain (python version correct, visual studio version correct, a c++11 compiler - not present on some LTS corporate linux distros, etc.)

The latter is particularly onerous for nodereport... things are already going badly for a customer, so we ask them to use nodereport, and now they need to a compiler set, possibly in violation of their devops policies on production machines, possibly just difficult on Windows.

**Comment by mattcolegate** [comment]
So this has become a larger piece of work very quickly - as well as the basic functionality being exposed via an Appmetrics API call, there is the issue of compiled code vs separate binaries, as well as getting the calls to work via the GUI. So in order to get a delivery in, this issue will be simplified as follows:

**This issue** will deal solely with requiring and exposing the nodereport and heapdump functionality via an Appmetrics API call. Both packages will be required from npm and therefore compiled from source.

**Another issue** will be raised to discuss provision of nodereport and heapdump via source code compilation, pre-built binaries on npm, absorbsion by appmetrics (I'll edit this later with the actual issue when it is raised)

**Yet another issue** will be raised when getting the GUI work done - the actual GUI work will be done in a work item, but we will need a PR for making the node env plugin a receiver so that it can talk to the GUI.
