### ISSUE TITLE
Add ability to modify appmetrics.properties at runtime

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics#328]
If we deploy appmetrics on a read only filesystem, how can we modify the properties file to set things like mqtt port and hostname.  Need a feature to enable us to pass values into the appmetrics constructor ?

**Comment by sam-github** [comment]
I suggest: every key/value that is valid in appmetrics.properties should be passable as a key/value in the options object of a `require('appmetrics')(options)` function. this will let me control app ID (if I want), as well as mqtt port/host (which I definitely do want). It also allows appmetrics to add runtime options in the future without modifying it's API.

**Comment by tobespc** [comment]
We have a fix for this @sam-github which will involve adding a new method to the api appmetrics.start().  This will give us the ability to not start the agent straight away so that we can configure everything first.  This won't affect users currently getting hold of the monitoring api but anyone just doing 

require('appmetrics');  

will now need an additional step of

var appmetrics = require('appmetrics');  
appmetrics.start();

We are going to add a configuration method that you call with the options to set any properties
