### ISSUE TITLE
gc duration is integer, sometimes zero

### ISSUE THREAD

**Issue by majgis** [RuntimeTools/appmetrics#338]
The gc duration is reported as an integer.  In some cases the event fires and the value is zero.  

I'm used to seeing http duration, also in ms, but reported as a float.

**Comment by majgis** [comment]
https://github.com/RuntimeTools/appmetrics/blob/master/src/plugins/node/gc/nodegcplugin.cpp#L142

Obviously from the code, this is the intended behavior.  It just doesn't meet expectation.

**Comment by tobespc** [comment]
So this is intentional to have duration as milliseconds as that keeps it inline with our Java monitoring solution.  I'm not sure what we can do other than update our docs to make it clear thats what we do.  Is this a blocker for you ?

**Comment by majgis** [comment]
No, this is fine.  Seeing events fire and return zero, knowing they were a fraction of a ms and were rounded down, was concerning at first, but seeing the data in production, the accuracy is acceptable.
