### ISSUE TITLE
Using appmetrics with statsd

### ISSUE THREAD

**Issue by imranbohoran** [RuntimeTools/appmetrics#341]
Hello

Appologies in advance as this might not be completely appmetrics related. 
We want to use appmetrics so that we can capture node specific metrics and also want to use statsd to capture custom metrics and send them all to a statsd daemon. We've looked at appmetrics-statsd but realised that the library doesn't allow configuring appmetrics (https://github.com/RuntimeTools/appmetrics-statsd/issues/5). Also there doesn't seem to be much activity in that project. Was wondering if using appmetrics-statsd is the only option we have if we want to use appmetrics and statsd in tandem or if there's an alternative approach.

**Comment by tobespc** [comment]
Hi, most of the work we do is around adding functionality to appmetrics and our core monitoring solutions (omr-agentcore).  the statsd library simply takes everything appmetrics produces and forwards to the statsd daemon.  It is still supported but the focus has been on this project in the short term.  
What sort of configuration options would you like to see ?

**Comment by imranbohoran** [comment]
Hi Toby, initially we'd like to be able to disable mqtt as we are not expecting to send any metrics to mqtt. But I would imagine the library being a wrap around appmetrics and statsd, it would be good to pretty much enable configuring both appmetrics and statsd the same way someone would configure it when using those libraries on their own. As far as I've understood, configuring statsd is possible from the appmetrics-statsd library, so I would hope having the same capability for appmetrics would also be sensible. Thanks.

**Comment by sam-github** [comment]
Maybe appmetrics-statsd (and friends) should support dependency injection, so appmetrics can be configured, then passed. This would allows using two adapters at once, and allow direct use of appmetrics as well as the adapters:

```
var appmetrics = require('appmetrics');
appmetrics.configure({mqtt: false})

var statsd = require('appmetrics-statsd')({appmetrics: appmetrics, prefix: 'my-scope.'});

var elk = require('appmetrics-elk')({appmetrics: appmetrics, ....});

appmetrics.start();
```

**Comment by sam-github** [comment]
^--- we'd probably need something like that in strong-supervisor to allow command line/env var configuration of the various adapters, and to have them use the appmetrics that supervisor depends on (instead of the internal dependency the adapters have now).

The adapters are well designed to be quick and simple to use ATM, but the internal dependency on appmetrics is inflexible, as @imranbohoran is running into.

**Comment by tobespc** [comment]
just looking at exactly that now @sam-github  :-)

**Comment by tobespc** [comment]
this is working for me when I install the latest appmetrics from git

var appmetrics = require('appmetrics');
appmetrics.configure({'mqtt':'off'});
var appstatsd = require('appmetrics-statsd').StatsD();

**Comment by sam-github** [comment]
OK, so the approach above works because `appmetrics` is now a global singleton?

**Comment by imranbohoran** [comment]
Hmm, As @sam-github says I guess it works this way since you had done a `require('appmetrics')` before `require('appmetrics-statsd).statsD()`. @tobespc is your recommendation we follow this approach or were you stating a work-around for here-and-now. IMHO the solution @sam-github suggested might be a bit more explicit on how `appmetrics-statsd` is configured.

**Comment by tobespc** [comment]
@imranbohoran This will work for here-and-now. :-)  We have only just fininshed the work on exposing appmetrics configuration via an api call so how we will expose this up to our additional packages (statsd, elk etc) is still in design

**Comment by imranbohoran** [comment]
@tobespc Thanks for that. Will keep this issue opened so we'll get notified when you complete the work. Thanks for your quick response. Much appreciated.

**Comment by sjanuary** [comment]
@sam-github `appmetrics` is not a global singleton right now, but the agent underneath it is, and the agent manages the properties, so that's why this works. It might be good for appmetrics itself to be a singleton to avoid anything strange happening.

**Comment by imranbohoran** [comment]
@tobespc So we tried this and we can't see that mqtt is disabled.

```
  var appmetrics = require('appmetrics');
  appmetrics.configure({'mqtt':'off'});
  var appmetricsStatsd = require('appmetrics-statsd').StatsD(null, "localhost", 8125, 'app-prefix.');
```

When the app starts up we see ```com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883```

I was expecting with `mqtt` set to `off`, no mqtt operations would take place. Am I missing something. Versions in use are;
```
    "appmetrics": "1.1.2",
    "appmetrics-statsd": "1.0.1"
```

**Comment by sam-github** [comment]
I think this was added in appmetrics 1.2

**Comment by imranbohoran** [comment]
Any chance getting 1.2.0 on npm please?

**Comment by tobespc** [comment]
we will be release 1.2.0 to npm in a few days, just finishing off release work.   In the meantime, you can use it now by cloning this git repo and installing from that locally

**Comment by sam-github** [comment]
`npm i --save RuntimeTools/appmetrics` will work until 1.2 is released, npm can install directly from github.

**Comment by sjanuary** [comment]
Closing as 1.2.0 is now released
