### ISSUE TITLE
Not including IBM

### ISSUE THREAD

**Issue by SirZach** [RuntimeTools/appmetrics#35]
Hey all,

I was looking through the licenses of appmetrics and noticed that things get complicated when you want to use the Eclipse plugin. What are your thoughts on releasing this without the IBM integration to keep the licensing simpler to just only Apache 2.0? What about a forked version not including the IBM/Eclipse integration?

Cheers,

Zach

**Comment by seabaylea** [comment]
The "agent core" that is under an IBM proprietary license is actually used for more than just the Eclipse IDE integration - it also provides other features such as an in-memory "flight recorder" storage of data (which can be extracted from a crash).

The intent is very much to open source that, and to do so as soon as possible - which would simplify the licencing. Would that be sufficient?

**Comment by tobespc** [comment]
@SirZach  The agent core module is now opensourced and the next release of appmetrics will be using this.  In the meantime, if you npm install directly from https://github.com/RuntimeTools/appmetrics, you will get the opensource code as well
