### ISSUE TITLE
http no longer reporting

### ISSUE THREAD

**Issue by majgis** [RuntimeTools/appmetrics#352]
We had two releases this week.  In the first one, the http reporting from appmetrics is firing. In the second one, the version of appmetrics and our wrapper package did not change, but appmetrics stopped reporting http events.  

I'm in the process of ruling out everything on our side.  One hypothesis is that appmetrics managed to get different binary dependencies, and the recent version bump for omr-agentcore adds weight to it, but it is unconfirmed at this point.  This is just a heads up in case it is an issue with appmetrics that might jump to someone's mind, otherwise, I'll report back when I find the exact cause.

**Comment by tobespc** [comment]
@majgis  thanks for the heads up, we'll investigate from our side as well

**Comment by hhellyer** [comment]
I've done a quick test on Mac and Linux (Ubuntu 16.10) that just does console logging of http events from appmetrics.monitor() using Node 6.5 and it seems to work OK so it looks like the events are firing at least locally.
What OS and Node versions were you using? Where were you listening for the events and not seeing them, locally or remotely?

**Comment by majgis** [comment]
Thanks for checking.  I confirmed that it is the same version of appmetrics and the binaries downloaded were the same.  I'm digging deeper to see what change in our code introduced the issue.

**Comment by majgis** [comment]
Node v4.6.0
CentOS 6.7
Listening for the events locally

**Comment by hhellyer** [comment]
I don't have access to a CentOS box right now but I have tried Node v4.6.0 and it seems to work.

Would you be able to try a simple test case? If you start this and just ping it with a browser or something like `curl http://127.0.0.1:1337/` you should see http requests being monitored:

```
var appmetrics = require('appmetrics');
var monitoring = appmetrics.monitor();

var http = require('http');

monitoring.on('http', function (data) {
    console.log('metric:');
    console.log('[time: ' + data.time + ']' );
    console.log('[duration: ' + data.duration + ']');
});

var req_count = 0;
var server = http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  req_count++;
  res.end('Request count: ' + req_count +'\n');
  if( req_count == 1000 ) {
          server.close();
  }
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```
 If this doesn't quite match what you are doing let me know what's different and hopefully we'll be able to get a simple test case that better matches your scenario.
Note that moving `require('http');` above `require('appmetrics');` will stop the test working. Your require order hasn't changed has it?

**Comment by majgis** [comment]
There was a change to how the server is being started. Thanks for your help, I'll compare this to what we have and report back.

**Comment by majgis** [comment]
The order of the require statements was the issue.

I was fixated on when the server was started vs when the monitor was started.

I didn't see this noted in the readme.  Also, it could output an warning message or log message.  Would you take a PR with one or more of these options?

**Comment by hhellyer** [comment]
Could you raise an issue? We'll update the docs and see if there's anything else we can do to make this clearer.
