### ISSUE TITLE
Divide error crashed node

### ISSUE THREAD

**Issue by imranbohoran** [RuntimeTools/appmetrics#362]
Hi

We had a problem recently where the node app was killed by SIGFPE. Looking at the logs it looks like its a divide error in `nodeloopplugin.cpp`

We found this error in the logs
```[1325067.125009] traps: node[1961] trap divide error ip:7fc0d0bdee19 sp:7ffdda6b8040 error:0 in libnodeloopplugin.so[7fc0d0bdd000+3000]```

We had some memory issues in the box where the application was running, so that possibly was the cause for this error. But thought of highlighting it here as this error killed the nodeapp. Has anyone else seen a similar issue before?

**Comment by NikCanvin** [comment]
I've asked around and so far nobody has seen this before... we'll check the code though and see if we see any likely cause

**Comment by sjanuary** [comment]
Fixed by #348
