### ISSUE TITLE
need outbound-http request when requests and trace enabled

### ISSUE THREAD

**Issue by yuecchen** [RuntimeTools/appmetrics#365]
I pasted two application: sample-rest-api is a rest-api provider application, and sample_app is a monitored application which call rest-api when user do query to it self:
[outbound-http.zip](https://github.com/RuntimeTools/appmetrics/files/715839/outbound-http.zip)

sample_app provider 2 APIs:
```
GET: /rest/api/getAllPets
POST: /rest/api/addOnePet
Sample Body:
{
"name":"Goggie","age":"3","type":"dog"
}
```
monitored codes have already in the application's code.

I can got the following log (request's data), when I trigger a request to sample_app:

```
{ time: 1484806501114,
  type: 'HTTP',
  name: '/rest/api/getAllPets',
  duration: 42.004436,
  request:
   Request {
     children: [],
     name: '/rest/api/getAllPets',
     type: 'HTTP',
     parent: undefined,
     id: 1,
     top: [Circular],
     timer:
      Timer {
        startTime: [Object],
        startTimeMillis: 1484806501114,
        timeDelta: 42.004436,
        cpuTimeDelta: -1 },
     active: false,
     context: { url: '/rest/api/getAllPets' },
     tracedStart: true,
     traceStopped: true,
     stack: 'Error\nat ServerResponse.res.end(/root/JanDemo/sample_app/node_modules/connect/lib/middleware/logger.js:149)\nat ServerResponse.module.exports [as send](/root/JanDemo/sample_app/node_modules/response-send/lib/response-send.js:108)\nat IncomingMessage.<anonymous>(/root/JanDemo/sample_app/index.js:82)\nat <module>.emitOne(events.js:96)\nat IncomingMessage.emit(events.js:188)\nat IncomingMessage.Readable.read(_stream_readable.js:381)\nat <module>.flow(_stream_readable.js:761)\nat <module>.resume_(_stream_readable.js:743)\nat <module>._combinedTickCallback(internal/process/next_tick.js:74)' } }
```

We can notice that: `children: [],`, which means the outbound http request is not collected. 

Could you please add the support on getting http outbound requests in request's data tree? when trace is enabled.

**Comment by tobespc** [comment]
@yuecchen We will take a look at this today and update later with an outlook on when this can be done

**Comment by ravigadekarla** [comment]
Toby, Please treat it as high priority as it's critical for Interconnect and for BAM. Thanks for your help

**Comment by seabaylea** [comment]
We'll also need this for OpenTracing support.

**Comment by tobespc** [comment]
still investigating

**Comment by sjanuary** [comment]
This needs a new probe to monitor http.get and http.request calls, which we don't currently do. Should be a new probe in order to differentiate outbound requests from inbound, events could be called "http-outbound". Assigning to myself to implement.

**Comment by sjanuary** [comment]
@yuecchen @ravigadekarla @seabaylea - please take a look at #371 if you would like to review or test the new probe.
