### ISSUE TITLE
visualizations for GC

### ISSUE THREAD

**Issue by sam-github** [RuntimeTools/appmetrics#370]
What StrongLoop had: Heap still in use after a minor or a major gc https://docs.strongloop.com/display/SLC/Available+metrics

What Trace has: GC run counts for scavenge and mark-sweep AND time spent for GC https://trace-docs.risingstack.com/docs/metrics

What Appdynamics has: Number of full gc and incremenatal GC per min
https://docs.appdynamics.com/display/PRO42/Node.js+Metrics

Its not clear in the above whether different vendors are using different names for the same thing, or whether appmetrics could access and display more information. Research needed.

**Comment by tobespc** [comment]
We are tracking the work for this on RTC @sam

**Comment by sjanuary** [comment]
Closing as discussion belongs in another project.

**Comment by sam-github** [comment]
Not tracked on RTC, can you reopen, @sjanuary ? Or add me as a member to the repo so I can :-)
