### ISSUE TITLE
Include http headers in object

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics#379]
Request from BAM to include http header information in the http event we emit

**Comment by tobespc** [comment]
looks like we already do this but have not put it in the docs

**Comment by seabaylea** [comment]
Are there any particular headers they're interested in? What's in the docs is our "API" and what isn't 
is technically "internals" ;-)

**Comment by tobespc** [comment]
"There are certain headers like X-Forwarded-For that we are interested in to do the required interrogation to populate dependencies."

**Comment by tobespc** [comment]
We emit the header as part of the JSON object that we already send

**Comment by seabaylea** [comment]
Ahh - it was added but not put in the docs ;-) Is it needed in requests as well as metrics? (we currently only add the extra data to metrics).

**Comment by tobespc** [comment]
extra request data is now added and additionally, outbound headers are also being emitted
