### ISSUE TITLE
Change dashboard layout to lead with HTTP charts

### ISSUE THREAD

**Issue by NikCanvin** [RuntimeTools/appmetrics#387]
request from @seabaylea , to align with likely User needs, please reorder dashboard charts as follows:

top row: HTTP Through-put; HTTP Incoming Requests; Average Response Time
next row's': merge (HTTP + other Probe) out-bound requests into 1 chart; Event Loop Latency; CPU; Memory; Heap; Environment

**Comment by sjanuary** [comment]
@NikCanvin this belongs in https://github.com/RuntimeTools/appmetrics-dash

**Comment by NikCanvin** [comment]
Thx Sian, moved: https://RuntimeTools/appmetrics-dash#10
