### ISSUE TITLE
appmetrics 2.0 have performance downgrade, compared with appmetircs 1.0

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#393]
For performance test, we are using acme-air as the sample application.   

1. Run one baseline test, record throughput, response time and CPU usage  
2. Run one performance test with ibm-apm + appmetrics v1.0.3, record throughput, response time and CPU usage  
3. Then run one performance test with ibm-apm + appmetrics v2.0.1, record throughput, response time and CPU usage  

Compare performance of 3 and 2 with 1 separately.

Here is the test result: 

Node.js Process CPU 100%	 |  % degradation vs. baseline for Transactions /sec	     | % increase vs. baseline for Average response time (ms)	    | % increase vs. baseline for overall CPU %
:---------------------------------|:--------------------|:---------------------------|:-----------------------
Resource Mode_v1.0.3	|9.17%	|1.73%	|1.18%
Resource Mode_v2.0.1	|14.54%	|4.23%	|1.92%

It seems the peformance of v2.0 have a lot of downgrade compared with appmetrics 1.0, especially on the throughput. 

Do we have more background work in resource mode (not enable request and trace) in appmetrics 2.0? Do we be able to disable them?

Or there is any other way to improve the performance.

**Comment by tobespc** [comment]
You have a lot more probes active, can you send me a snippet of the code where you are enabling appmetrics please

**Comment by mattcolegate** [comment]
@xiaoshimimi, respond to the above comment.

**Comment by mattcolegate** [comment]
@xiaoshimimi, response please

**Comment by xiaoshimimi** [comment]
we will try to disable probes that 1.0.3 don't have and retest the performance

**Comment by xiaoshimimi** [comment]
The performance got better with the following event disabled:

```
healthcenter.disable('eventloop');
healthcenter.disable('express');
healthcenter.disable('socketio');
healthcenter.disable('memcached');
healthcenter.disable('mqlight');
healthcenter.disable('postgresql');
healthcenter.disable('mqtt');
healthcenter.disable('redis');
healthcenter.disable('riak');
healthcenter.disable('oracledb');
healthcenter.disable('oracle');
healthcenter.disable('strong-oracle');
```
So we found the root cause of performance downgrade is new features enabled. 

Do we think we still have buffer to improve the performance with those new features enabled? Because those features are resource level monitoring, we should make sure resource monitoring basically not affect user's application.

**Comment by tobespc** [comment]
There is not much we can do to improve the probes, its always going to be the case that if you want more data, you pay a performance price

**Comment by sam-github** [comment]
Though generally, an app wouldn't be using every single one of those probes, or even a majority.

Do you have a synthetic benchmarking app that attempts to use every supported DB?

**Comment by xiaoshimimi** [comment]
Could we possible to provide a feature: disable all DB evens that not used in the monitored application? It might be easy to find: as long as there is no require('xxx'); (e.g. require('mongodb'); ) that means this application is not using that DB (e.g. mongodb).

**Comment by tobespc** [comment]
we won't be triggering events if you are not using the DB in the application

**Comment by sjanuary** [comment]
> Though generally, an app wouldn't be using every single one of those probes, or even a majority.

It's probably just one or two probes causing the change in performance, or even just the eventloop one.  As Toby says if a module isn't required then the associated probe will have 0 effect.

Being able to disable all probes (either by default or by one LOC instead of 20) might be worth doing.

**Comment by NikCanvin** [comment]
could we enable toggling the probes on/off?
  (add controls to dash board too, if possible)

I like the group off (and on) action idea, in the previous comment

**Comment by sam-github** [comment]
@sjanuary do you have reason to suspect the eventloop probe? It's pure c++, and pretty low overhead, I would be suspecting one of the javascript monkey-patching probes, but guess work is not a replacement for banchmarking.

**Comment by sjanuary** [comment]
@sam-github no, I don't suspect the eventloop probe for any reason it was more to state that that would definitely be running even if none of the probes were as I'm not sure what kind of test application is being used here. Would definitely be good to see/do some benchmarking.

**Comment by xiaoshimimi** [comment]
@sjanuary we need your double confirm that for the following events, we don't need to disable it actively, as long as we don't require them in application, they will have 0 affect to performance. 

```
healthcenter.disable('express');
healthcenter.disable('socketio');
healthcenter.disable('memcached');
healthcenter.disable('mqlight');
healthcenter.disable('postgresql');
healthcenter.disable('mqtt');
healthcenter.disable('redis');
healthcenter.disable('riak');
healthcenter.disable('oracledb');
healthcenter.disable('oracle');
healthcenter.disable('strong-oracle');
```

That's important for us to decide whether we need to provide options to user to enable or disable those events.

**Comment by sjanuary** [comment]
@xiaoshimimi - that's right, as long as neither your application nor any of its dependencies require those modules.

**Comment by xiaoshimimi** [comment]
@sjanuary Thank you :+1:

**Comment by tobespc** [comment]
can this be closed now ?

**Comment by xiaoshimimi** [comment]
Yes, thank you.
