### ISSUE TITLE
Glitches in npm doc

### ISSUE THREAD

**Issue by crandmck** [RuntimeTools/appmetrics#397]
The README as displayed in https://www.npmjs.com/package/appmetrics has some layout issues, for some headers, e.g.:
![2017-02-23_1045](https://cloud.githubusercontent.com/assets/2925364/23273815/56456148-f9b5-11e6-8b0d-efd8e2c22fdc.png)

I see why this is happening and could easily fix it in a PR, if it would be welcome(?)

**Comment by sam-github** [comment]
@tobespc @NikCanvin Rand is an IBM ID (ex-Strongloop doc lead), architect of the express docs, and doesn't need CLA.

**Comment by mattcolegate** [comment]
@crandmck A PR would be most welcome, thank you :-)

**Comment by mattcolegate** [comment]
PR pulled, docs look good, links work. A++ Gitter, would pull PR request again.
