### ISSUE TITLE
Does appmetrics need better node version detection?

### ISSUE THREAD

**Issue by rmg** [RuntimeTools/appmetrics#407]
Now that node-chakracore nightlies are available for Windows, Mac, and Linux, I've been giving it a try.

Running `npm i appmetrics` fails as expected, but the error it prints out suggests this might be a source of problems in the future.

> Unsupported version v8.0.0-nightly2017031520fa6b1909. Exiting.

It appears to be failing simply due to the version number. As long as node-chakracore manages to pull off their goal of binary compatability this won't be an issue. If anything v8 or chakra specific comes in to play in appmetrics then it might warrant more elaborate version checking.

Here's `process.versions` in case it helps any:
```
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '8.0.0-nightly2017031520fa6b1909',
  chakracore: '2.0.0.0',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '53',
  openssl: '1.0.2k' }
```

**Comment by tobespc** [comment]
@rmg I agree, this is an issue .  We will see what we can do to improve things

**Comment by mattcolegate** [comment]
The error message comes from extract_all_binaries.js - we don't have appmetrics binary builds for Node 8 yet, so it's griping at the node version number. In the meantime I've asked @rmg to try installing from source using `npm i RuntimeTools/appmetrics.git`

**Comment by mattcolegate** [comment]
Note that @rmg says this blocks `npm i -g apiconnect` - @tobespc says that if you can get it building from source, npm should recognise you already have it and not try and download the binaries from npm

**Comment by sjanuary** [comment]
I'm wondering if appmetrics could/should fall back to node-gyp rebuild if the binaries aren't available for a particular version. Thoughts?

**Comment by gibfahn** [comment]
Fallback to build from source if you can't find binaries is what a lot of other node modules (e.g. `node-sass`) do, seems like a good way to go (to me).

**Comment by gibfahn** [comment]
Had a chat with @tobespc and falling back to building from source if a binary isn't available (unsupported platform or version) should be fine.

**Comment by mattcolegate** [comment]
We also need to remove versions we don't support anymore (like 5)

**Comment by gibfahn** [comment]
@mattcolegate yeah, ideally you'd have a message like `Couldn't find a prebuilt binary, falling back to building from source`.

**Comment by rmg** [comment]
As a long time node user/developer, falling back to building from source is definitely the behaviour I was expecting.

**Comment by sjanuary** [comment]
Please see #410 for implementation of fallback to building from source
