### ISSUE TITLE
HTTPS probe

### ISSUE THREAD

**Issue by Fred2MTL** [RuntimeTools/appmetrics#409]
Hi
There is an HTTP probe, what runs correctly and only for HTTP 'action'.
But, how to monitor HTTPS server (not the express part), on the same basics as HTTP probe ? I didn't anything about that in the documentation, the past issues or in the code.

**Comment by sjanuary** [comment]
It would be good to do this at some point.  As suggested, it will require a new probe to be implemented.  Tagged as enhancement.

**Comment by anthonywebb** [comment]
I am in need of tracking https-outbound calls that our server is making using the 'request' npm lib.  Currently it appears that the 'http-outbound' probe is catching the http stuff.  But not the https stuff.  Is this a pretty straight forward addition?  Just wondering why it was excluded to begin with, it seems like http probes would catch both?

**Comment by sjanuary** [comment]
It wasn't explicitly excluded, but appmetrics probes match the module name exactly and **https** is implemented as a separate module in Node, so the http probe only catches calls made via the **http** module. It will be fairly simple to implement the https probe, it just hasn't been done yet.

**Comment by anthonywebb** [comment]
Anyone else need this as much as me?  Most apps these days make http requests to https addresses.  Would be a nice addition.

**Comment by tobespc** [comment]
@anthonywebb Yep, this is something we intend to do.  Its on our radar and we hope to get to this very soon.  We also welcome contributors to this project :-)
