### ISSUE TITLE
Express probe removed?

### ISSUE THREAD

**Issue by anthonywebb** [RuntimeTools/appmetrics#425]
I've been hunting around for an explanation as to why the express probe was removed?  Anyone know what happened there?  Will it be coming back?  Workarounds?  Anything else new in 3.0 that makes it a worthy upgrade?

**Comment by tobespc** [comment]
We removed it as it wasn't giving any extra data over the http probe and, as a result, we were getting duplicate data  

https://github.com/RuntimeTools/appmetrics/pull/406
https://github.com/RuntimeTools/appmetrics/issues/390

We will put the express probe if we get additional data over http but for them moment, we don't have any requirement to do so.

If you were using the express probe, the http probe will be the replacement

**Comment by anthonywebb** [comment]
@tobespc I saw that and ultimately ended up using the express probe for inbound over the http one because it contained the statusCode, am I overlooking where status code is on the http probe?

**Comment by tobespc** [comment]
We added status code in https://github.com/RuntimeTools/appmetrics/pull/401

this will be in the upcoming 3.0.0 release on NPM that we are trying to get out the door this week

**Comment by anthonywebb** [comment]
OK great, I will watch for it.
