### ISSUE TITLE
application is not using the appmetrics in ./node_modules

### ISSUE THREAD

**Issue by yuecchen** [RuntimeTools/appmetrics#439]
We have two application, they are using exactly the same appmetrics (v3.0 dev). 

One we can see the requestHeader in 'http' event, but for the other we can't. 

It seems the other application is not using the appmetrics in it's ./node_modules. But we cannot find which appmetrics it is using. 

Could you please help do some debug on our environment?
(will attach environment information through mail)

**Comment by yuecchen** [comment]
I found: 
./opt/ibm/node/lib/node_modules/apiconnect-collective-member/node_modules/appmetrics
./opt/ibm/node/lib/node_modules/apiconnect-collective-member/node_modules/appmetrics/binaries/appmetrics

and: 
./root/.npm/registry.npmjs.org/appmetrics
./root/.npm/appmetrics

It seems ./opt/ibm/node/lib/node_modules/apiconnect-collective-member/node_modules/appmetrics is the appmetrics bound by APIC?

**Comment by tobespc** [comment]
this is really a question for APIC, not something I can answer

**Comment by tobespc** [comment]
closing as needs to be raised with APIC to get them to update appmetrics in their bundling
