### ISSUE TITLE
Prometheus exporter

### ISSUE THREAD

**Issue by yannickl** [RuntimeTools/appmetrics#443]
Hi there,

I think I'll be off topic, but I would know if there is any plan to support Prometheus monitoring solution?

I know you use a push pattern (with mqtt) while Prometheus uses a pull pattern, but I wondering whether adding a `/metrics` endpoint could be possible to gather all the metrics?

Best,

Yannick

**Comment by tobespc** [comment]
@yannickl We are investigating Prometheus support at the moment and how we can support that monitoring solution.   I'll provided further info when we have made some progress

**Comment by sjanuary** [comment]
Implementation has been started in a new project - https://github.com/RuntimeTools/appmetrics-prometheus
