### ISSUE TITLE
http and request events are not firing.

### ISSUE THREAD

**Issue by Swapnil89** [RuntimeTools/appmetrics#452]
Hi Please see below sample code.

```js
const express = require('express')
const app = express()
var port = process.env.PORT || 3000;
var appmetrics = require('appmetrics');
var monitor = appmetrics.monitor();
appmetrics.enable('http');
appmetrics.enable('request');
monitor.on('request', function (request) {
        console.log('request', request);
});
monitor.on('http', function (http) {
        console.log('http', http);
});
app.get('/', function (req, res) {
  res.send('Hello World!')
})
app.listen(port, function () {
  console.log('Example app listening on port 3000!')
})
```

Whenever I fire localhost:3000 from browser. I get 'Hello World!' reply but logs doesn't show any request or http event. Can somebody help me to point out issue.
I am using latest appmetrics version.

Thanks in Advance.

**Comment by tobespc** [comment]
@Swapnil89 I'll take a look and update shortly

**Comment by mattcolegate** [comment]
@Swapnil89 Can you try moving the 
```javascript
var appmetrics = require('appmetrics');
```
line to the top of the code? Node Application Metrics instruments modules when they are 'required' - so because you've required express before requiring appmetrics, it hasn't instrumented your express instance.

**Comment by sam-github** [comment]
This seems a common problem, perhaps appmetrics should look at the require cache when starting up, and report a problem if one of its instrumented libs has already been required?

**Comment by mattcolegate** [comment]
@Swapnil89 How did my suggestion work out for you? Any good?

**Comment by mattcolegate** [comment]
@Swapnil89 I've commented on your StackOverflow question with the same suggestion.

**Comment by mattcolegate** [comment]
@Swapnil89 Just tested this out - with your code as is I could recreate your scenario; once I moved the `require(appmetrics)` line to the top of the file I started getting the console logging http request objects. I'm closing the issue as resolved, please reopen if you would like further help. Also, if you could mark my answer correct on StackOverflow I'd be grateful! @sam-github might be an idea to raise the require cache scanning as a separate issue?
