### ISSUE TITLE
Expose patched function name in aspects framework

### ISSUE THREAD

**Issue by seabaylea** [RuntimeTools/appmetrics#46]
The aspects patching framework allows you to specify an array of function names to patch. eg. for aspect.around:

    var functionNames = [];
    aspect.around(target.prototype, functionNames,
        function(target, args) {},
        function(target. args, rc) {}
    );

This means you can patch multiple functions in the same way with the same code, but there's no way of knowing the name of the actual function that is running. This is useful if you want to add it to the raised monitoring event.

Passing the function name through to the function callbacks as an additional (last) parameter provides access to the name of the function without breaking existing code, eg:

    var functionNames = [];
    aspect.around(target.prototype, functionNames,
        function(target, args, funcName) {},
        function(target. args, rc, funcName) {}
    );

**Comment by seabaylea** [comment]
@tunniclm Any view on the addition of the patched function name as a new last parameter passed to the supplied before and after callbacks?

Note that this only applies to aspect.before(), aspect.after() and aspect.around(). The aspect.aroundCallback() call doesn't take a function name - you should already have that from a previous call to aspect.before() or aspect.around().

**Comment by tunniclm** [comment]
@seabaylea This approach seems reasonable to me, adding as the last argument should prevent breakage of existing usage code.

**Comment by seabaylea** [comment]
Closing with PR #49
