### ISSUE TITLE
No response information with http-outbound

### ISSUE THREAD

**Issue by bkez322** [RuntimeTools/appmetrics#472]
My httpOutbound object does not not contain information about the response and I cannot figure out why. 

My code is as follows:
```
monitor.on('http-outbound', function(httpOutbound) {
        console.log(httpOutbound);
    });
```

An example of output I get is as follows:
```
{ time: 1505169474204,
  method: 'GET',
  url: 'my-url.com:8080',
  duration: 3.009992,
  statusCode: undefined,
  contentType: 'undefined',
  requestHeaders: { host: 'my-url.com:8080' } }
```

I can independently verify that my app is in fact receiving a response complete with a status code. It's interesting that the duration property is populated which implies that the appmetrics library knows when a response was received, but I do not understand why statusCode and contentType are undefined.

**Comment by stalleyj** [comment]
I'll look into this issue

**Comment by stalleyj** [comment]
@bkez322 Are you passing a callback to the request ? If you do not pass a callback, the statusCode and contentType will be undefined which is the expected behaviour.

**Comment by bkez322** [comment]
When we switched from using the request library to the builtin http module the response information  started to work correctly.
