### ISSUE TITLE
https-outbound data missing with Node.js 8.9.0 release

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics#490]
Still working with Node.js v6

**Comment by sjanuary** [comment]
Seems like this is a very recent change, between versions 8.8.0 and 8.9.0. Probably due to https://github.com/nodejs/node/commit/5118f3146643dc55e7e7bd3082d1de4d0e7d5426#diff-dc1e3006797f52c8d34db55abaf1fe7e

**Comment by stalleyj** [comment]
Fixed by https://github.com/RuntimeTools/appmetrics/pull/491
