### ISSUE TITLE
appmetrics build issues as side effect of including bluemix autoscaling into ibm dedicated bluemix build

### ISSUE THREAD

**Issue by pdykes** [RuntimeTools/appmetrics#504]
Team,

I use node and bluemix-autoscaling-agent, last friday did a full rebuild and deploy and all worked.  When I was doing a rebuild/deploy today (no code change, just rebuilding so I can take the holiday off), I see the bluemix-autoscaling-agent is updated (not sure if related), but it pull in metrics.

I can build locally, but in bluemix dedicated toolchain builds I get this error:

 ACTION binding_gyp_appmetrics_target_Set_appmetrics_reported_version_build_level Release/obj.target/appmetrics/geni/appmetrics.cpp
infile: ./src/appmetrics.cpp
outfile: /home/pipeline/2aae0ea2-c211-4f04-8a9c-3574decad3cf/node_modules/bluemix-autoscaling-agent/node_modules/appmetrics/build/Release/obj.target/appmetrics/geni/appmetrics.cpp
Replacing '"99\.99\.99\.29991231"' with '"3.1.3.201711201509"'
  CXX(target) Release/obj.target/appmetrics/geni/appmetrics.o
In file included from ../node_modules/nan/nan.h:199:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:22:
../node_modules/nan/nan_maybe_pre_43_inl.h: In function 'Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Handle<v8::Object>, v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_pre_43_inl.h:158:44: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
                  !(current & v8::ReadOnly) &&               // writable AND

Workarounds? I have a turkey calling my name ;-)

Thanks!

**Comment by stalleyj** [comment]
I have passed this problem on to Bluemix autoscaling team

**Comment by stalleyj** [comment]
@pdykes Is this still an issue ?

**Comment by pdykes** [comment]
I have to check, hopefully next week. Perry

**Comment by stalleyj** [comment]
Closing this as no response from original raiser, re-open if this is still a problem

**Comment by piotr-s-brainhub** [comment]
I have a problem with that - I updated `yarn.lock` so `appmetrics` version changed from `4.0.1` into `5.0.2` so build fails with:
```
   Release/obj.target/appmetrics/geni/appmetrics.cpp:92:30: note: candidate is:
   In file included from /tmp/contents13/deps/0/node/include/node/node.h:63:0,
                    from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
   /tmp/contents13/deps/0/node/include/node/v8.h:2645:7: note: int v8::String::WriteUtf8(char*, int, int*, int) const
      int WriteUtf8(char* buffer,
          ^
   /tmp/contents13/deps/0/node/include/node/v8.h:2645:7: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘char*’
   Release/obj.target/appmetrics/geni/appmetrics.cpp: In function ‘void emitMessage(uv_async_t*, int)’:
   Release/obj.target/appmetrics/geni/appmetrics.cpp:451:44: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1740) [-Wdeprecated-declarations]
            listener->callback->Call(argc, argv);
                                               ^
   make: *** [Release/obj.target/appmetrics/geni/appmetrics.o] Error 1
   make: Leaving directory `/tmp/app/node_modules/appmetrics/build'
   gyp ERR! build error 
   gyp ERR! stack Error: `make` failed with exit code: 2
   gyp ERR! stack     at ChildProcess.onExit (/tmp/contents13/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
   gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
   gyp ERR! System Linux 4.15.0-47-generic
   gyp ERR! command "/tmp/contents13/deps/0/node/bin/node" "/tmp/contents13/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
   gyp ERR! cwd /tmp/app/node_modules/appmetrics
   gyp ERR! node -v v10.9.0
   gyp ERR! node-gyp -v v3.7.0
   gyp ERR! not ok
```
