### ISSUE TITLE
Using nodemon with appmetric causes heapdumps

### ISSUE THREAD

**Issue by baens** [RuntimeTools/appmetrics#517]
Summary
----------
When trying to use nodemon (or any package that does service restarting) with appmetrics causes the application to crash on restart and produce a heapsnapshot file.

Steps to reproduce
--------------------
Setup a project (using yarn)
```
yarn init -y
yarn add nodemon express appmetrics
```

index.js without appmetrics
```
const express = require('express');

const app = express();

app.get('/',(request, response) => response.send('test'));

app.listen(8080);
```

index.js with appmetrics
```
const express = require('express');
const appmetrics = require('appmetrics');

const app = express();

app.get('/',(request, response) => response.send('test'));

app.listen(8080);
```

Running the application with `yarn nodemon index.js`

Add `console.log` just after the import statements

Expected behavior
-------------------
Nodemon restarts the service and the console.log message is displayed

Current behavior
-----------------
Application crashes with a heapsnapshot produced and no restart happens. To get application to restart you have to stop nodemon.

Versions
---------
node -v: v8.9.4
yarn -v: 1.3.2

**Comment by hhellyer** [comment]
Appmetrics includes the heapdump module, both nodemon and heapdump use SIGUSR2. nodemon uses SIGUSR2 to restart the application and heapdump uses it to generate a heap dump.

You should be able to avoid this issue by using the `NODE_HEAPDUMP_OPTIONS` environment variable to prevent heapdump using SIGUSR2:

`> env NODE_HEAPDUMP_OPTIONS=nosignal nodemon -r heapdump index.js`

**Comment by baens** [comment]
So 

`> env NODE_HEAPDUMP_OPTIONS=nosignal nodemon -r heapdump index.js`

Crashes with

```
Error: Cannot find module 'heapdump'
```

However

`> env NODE_HEAPDUMP_OPTIONS=nosignal nodemon index.js`

Does seem to work! 

Thank you!
