### ISSUE TITLE
No CPU data on z/OS

### ISSUE THREAD

**Issue by matthewpwilson** [RuntimeTools/appmetrics#524]
No 'cpu' events are emitted on z/OS using version 3.1.3 and appmetrics-dash shows 'No data available'. If this feature is not supported it would be good to have it documented in the README.

My test case (works fine on my Linux workstation):
"use strict";
let appmetrics = require('appmetrics');
let monitoring = appmetrics.monitor();
let http = require('http');

monitoring.on('cpu', function(data) {
  console.dir(data);
});

let server = http.createServer(function (request, response) {
	  response.write('Hello Monitored World!'); 
	  response.end(); 
});

console.log("Started test.js at " + (new Date()))
server.listen(28225);

**Comment by matthewpwilson** [comment]
Still seeing this with 4.0.1

**Comment by mattcolegate** [comment]
CPU event is indeed not supported on z/OS - marked as such in the README.
