### ISSUE TITLE
Review 'ibmapm-embed' dependency (licensing and authorship issues)

### ISSUE THREAD

**Issue by honzajavorek** [RuntimeTools/appmetrics#530]
The `ibmapm-embed` package depends on `request`, which transitively depends on `bcrypt-pbkdf`, which has unclear licensing and authorship (see https://github.com/request/request/issues/2971). My concerns are explained in https://github.com/joyent/node-sshpk/issues/37#issuecomment-401051047 This problem spreads through `ibmapm-embed` and affects `appmetrics` as well.

**Comment by tobespc** [comment]
@honzajavorek Thanks for raising this, I'll take a look at these dependencies and update shortly

**Comment by honzajavorek** [comment]
The issue has been resolved by releasing `bcrypt-pbkdf@1.0.2` a few hours ago. Since it is a patch version, it propagates to new installs up the dependency tree. Details [here](https://github.com/joyent/node-sshpk/issues/37#issuecomment-401216983). Thank you!
