### ISSUE TITLE
Error: Cannot find module './appmetrics'

### ISSUE THREAD

**Issue by shiyanf** [RuntimeTools/appmetrics#539]
When I try the appmetrics 4.0.0 on Ubuntu, I get this error.

 

[root@cn-icp-01 testware]# kubectl logs acmeairam-cc9dd6c58-8kl42
module.js:549
    throw err;
    ^

Error: Cannot find module './appmetrics'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/apps/acmeair-appmetrics/node_modules/appmetrics/index.js:44:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

ENV:
root@acmeairam-cc9dd6c58-fkd4p:/var/apps/acmeair-appmetrics# node -v
v8.10.0
root@acmeairam-cc9dd6c58-fkd4p:/var/apps/acmeair-appmetrics# uname -a
Linux acmeairam-cc9dd6c58-fkd4p 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@acmeairam-cc9dd6c58-fkd4p:/var/apps/acmeair-appmetrics# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by shiyanf** [comment]
Package.json:

[root@cn-icp-01 acmeair-appmetrics]# cat package.json 
```
{
  "name": "acmeair",
  "version": "0.0.4",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "appmetrics": "^4.0.0",
    "appmetrics-dash": "^4.0.0",
    "appmetrics-prometheus": "^2.0.0",
    "appmetrics-zipkin": "^1.1.1",
    "async":    "0.2.x",
    "express":  "4.11.x",
    "morgan":  "1.5.x",
    "body-parser": "1.11.x",
    "method-override": "2.3.x",
    "cookie-parser": "1.3.x",
    "mongodb":  "2.0.x",
    "node-uuid":"1.3.3",
    "async": "0.2.10",
    "csv": "0.2.4",
    "log4js": "0.6.12",
    "ttl-lru-cache": "0.0.2",
    "nano":"5.10.x",
    "cassandra-driver":"2.0.x",
    "stats-lite":"1.0.3",
    "circuit-breaker":"0.0.4"
  }
}

```

**Comment by tobespc** [comment]
can you provide details of the dockerfile you are using to build this environment please or, even better, provide a machine we can log into to see the issue.  We have appmetrics running on ubuntu without any problems so I'm wondering if its not installing correcrtly into your container

**Comment by shiyanf** [comment]
https://github.com/acmeair/acmeair-nodejs
This is the application I deployed.

**Comment by sjanuary** [comment]
@shiyanf this message means that the **native** appmetrics module can't be found. It has possibly failed to build during the npm install phase. Is there anything in your Docker build output that could help?

**Comment by shiyanf** [comment]
@sjanuary It should be the root cause, the ./appmetrics.node is not build rightly. But my environment is out of service now.  You can build it (https://github.com/acmeair/acmeair-nodejs) in your environment, if you have environment.  Or if you have environment, I can reproduce it in your env. Thanks.

**Comment by tobespc** [comment]
@shiyanf we need more information from you.  That Dockerfile you have provided fails to run so we cannot test with that.   What version of Node are you running with ?  If you don't run with Docker but just run acmeair from the command line, does that work for you ?  Unfortunately, without the build log from Docker showing what has been installed (and possibly failed) we are a bit stuck.  Are you still running this test at all ?

**Comment by sjanuary** [comment]
@shiyanf I downloaded the acmeair-nodejs project, added the 4 appmetrics dependencies to package.json and added `require('appmetrics-dash').attach()` to line 17 of app.js.  I then ran `docker build -t acmeair .` and then `docker run acmeair` on my local machine and it ran without error.  I also tried changing the require statement to `require('appmetrics').monitor()`, which also ran without error.

**Comment by shiyanf** [comment]
@sjanuary You can close this one now, once my env back, I will reproduce this, and update issue. Thanks.

**Comment by yasir-rafiq** [comment]
facing the same problem any solution?

**Comment by mattcolegate** [comment]
@yasir-rafiq it turned out that appmetrics wasn't building correctly in that user's environment - check you have an `appmetrics.node` file in your `appmetrics` directory and review the installation logs for build errors
