### ISSUE TITLE
Document 'initialized' event in the monitor() API

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#54]
Currently this is mentioned in an example, but not documented as an event.
It should also be mentioned in the `getEnvironment()` description that it should not be called prior to the `'initialized'` event.

**Comment by mattcolegate** [comment]
@tunniclm, please comment on the pull request and then close this issue if you're happy with the resolution.

**Comment by tunniclm** [comment]
Sorry, this slipped through the cracks in my inbox. Retroactively, this looks good to me!
