### ISSUE TITLE
Please update "tar" dependency to more recent version

### ISSUE THREAD

**Issue by raydenx** [RuntimeTools/appmetrics#548]
The version of "tar" that is bundled with appmetrics is over two years old. While a quick search for known vulnerabilities in this version of "tar" didn't turn up anything marked as such, archiving utilities such as these are frequently found to have vulnerabilities (eg. path traversal vulnerabilities - handling of filenames with "../")  and patched. 
Is it possible to upgrade "tar" to the latest version?

**Comment by mattcolegate** [comment]
I believe we're now pulling in the latest `tar`, so am closing this issue.
