### ISSUE TITLE
The processMean and systemMean are not correct.

### ISSUE THREAD

**Issue by shiyanf** [RuntimeTools/appmetrics#558]
Node: v8.12.0
Env: Redhat 7.6

The processMean and systemMean are both higher than 0.5, it is not correct for systemMean.
{ time: 1543377323769,
  process: 0.563199,
  system: 0.534872,
  processMean: 0.5729831764705883,
  systemMean: 0.5313571764705882 }

**Comment by shiyanf** [comment]
We have a internal issue is opened for this. 

 The service CPU usage show as about 25%, but from nmon or top, the Node process CPU usage is about 50%
<img width="758" alt="2018-12-03 1 09 29" src="https://media.github.ibm.com/user/45844/files/b7f330c8-f6fc-11e8-97a5-94f94bf6dd89">

top - 21:09:50 up 19 days, 21:37,  1 user,  load average: 1.30, 1.17, 1.24
Tasks: 109 total,   2 running, 107 sleeping,   0 stopped,   0 zombie
%Cpu(s): 20.4 us,  5.1 sy,  0.0 ni, 61.1 id,  0.2 wa,  0.0 hi,  0.7 si, 12.6 st
KiB Mem :  3880532 total,  1236128 free,   311432 used,  2332972 buff/cache
KiB Swap: 16777212 total, 16777212 free,        0 used.  3222024 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
31320 root      20   0 1691544 108336  15200 R  45.8  2.8  45:25.54 node
27085 root      20   0 1106096  84812   9484 S  17.9  2.2 451:27.37 mongod
    9 root      20   0       0      0      0 S   0.7  0.0  35:16.92 rcu_sched

**Comment by tobespc** [comment]
What environment are you running this test in ?  Can you provide a test case to recreate this with please

**Comment by shiyanf** [comment]
@tobespc 
1. We run a Node.js application on redhat 7 with on-premise mode. You can download it from https://github.com/acmeair/acmeair-nodejs, there is git readme about how deploy it. 

2. Then you need adjust your cpu cores to 2, by run the command.
```
echo 0 | sudo tee /sys/devices/system/cpu/cpu1/online
echo 0 | sudo tee /sys/devices/system/cpu/cpu2/online
...
```
3. Run JMeter to make your CPU usage to about 50%. You can refer to below jmeter file.

[nodedcperftest.zip](https://github.com/RuntimeTools/appmetrics/files/2652028/nodedcperftest.zip)

4. You will find the data of Event: 'cpu' are not correct. You can compare the processMean and systemMean to the output of "top" or "nmon".

**Comment by mattcolegate** [comment]
@shiyanf I've tested that the CPU plugin does react when the number of processors available is changed in this way, and it does - and the internal numbers make sense.

I'm wondering if your problem is really with Appmetrics, due to your CPU object:
{ time: 1543377323769,
process: 0.563199,
system: 0.534872,
processMean: 0.5729831764705883,
systemMean: 0.5313571764705882 }

From the README:

Event: 'cpu'

Emitted when a CPU monitoring sample is taken.

    data (Object) the data from the CPU sample:
        time (Number) the milliseconds when the sample was taken. This can be converted to a Date using new Date(data.time).
        process (Number) the percentage of CPU used by the Node.js application itself. This is a value between 0.0 and 1.0.
        system (Number) the percentage of CPU used by the system as a whole. This is a value between 0.0 and 1.0.

There's no processMean or systemMean values. Where are they being generated?

**Comment by mattcolegate** [comment]
@corbint pointed me to https://github.com/RuntimeTools/appmetrics-dash as a place where we share that kind of data via a REST API https://github.com/RuntimeTools/appmetrics-dash/blob/c8284197ccb84a7ccecf85e990232bf05ef40500/REST-API.md, so I'll work on that being where the data is coming from.

Having looked at the code, the systemMean and the processMean are calculated by averaging the system and process values of every CPU event they receive. It's not supposed to represent the current CPU usage by the processes or the system, but an average over the lifetime of the running program. If you run your program at 100% CPU for half of the time, but 0% the other half of the time, then processMean would show 50% usage. Would that perhaps account for the discrepancy you're observing? I know JMeter can have a long lead-in time before thrashing applications - maybe you're collecting a lot of low CPU readings before the program is being driven?

I'll attempt to run Acme Air with appmetrics-dash and see if it looks significantly incorrect.

**Comment by mattcolegate** [comment]
I've also just found out that `top` shows CPU usage based on a single core percentage:

https://superuser.com/questions/457624/why-is-the-top-command-showing-a-cpu-usage-of-799

Appmetrics averages out it's CPU usage by number of cores, so if one core is 50% loaded with Node and another is 0% loaded then we show 25% load across the whole CPU. `top` would show 50% load for Node.

To put it another way, if your Node process was using 75% of both cores, Appmetrics would show the load as 75%, but `top` would show 150% load for the node process.

Given you're running your test on two cores this might very well explain the numbers that are being seen.

**Comment by shiyanf** [comment]
@mattcolegate Thanks for your response. You mean the systemMean and the processMean are the average over the lifetime of the running program, instead of last 5 seconds or something just like top command?  It doesn't make sense.

**Comment by mattcolegate** [comment]
@shiyanf Yes, that is correct. Also that `top`'s CPU usage percentage is based on the percentage of a single core that the process is using ( 1 core = 100%) instead of across all cores like Appmetrics (n cores = 100%). I believe if you press `Shift + i` when using `top` it will change the percentages to look more like Appmetrics.

**Comment by mattcolegate** [comment]
From your own `top` example in the comments:

top - 21:09:50 up 19 days, 21:37, 1 user, load average: 1.30, 1.17, 1.24
Tasks: 109 total, 2 running, 107 sleeping, 0 stopped, 0 zombie
%Cpu(s): **20.4 us, 5.1 sy, 0.0 ni, 61.1 id**, 0.2 wa, 0.0 hi, 0.7 si, 12.6 st
KiB Mem : 3880532 total, 1236128 free, 311432 used, 2332972 buff/cache
KiB Swap: 16777212 total, 16777212 free, 0 used. 3222024 avail Mem

The %CPU(s) line shows that across your system, the CPUs are 20.4% engaged in userspace work, 5.1% engaged in kernalspace work, and 61.1% idle.

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
31320 root 20 0 1691544 108336 15200 R **45.8** 2.8 45:25.54 node
27085 root 20 0 1106096 84812 9484 S 17.9 2.2 451:27.37 mongod
9 root 20 0 0 0 0 S 0.7 0.0 35:16.92 rcu_sched

This shows your node process as using 45.8% of one CPU - you clearly have more CPUs available however, as the overall userspace percentage is 20.4%. If you only had one CPU available then the numbers would be much closer.

Note that Appmetrics is showing 25% system CPU usage, which is consistent with the %CPU(s) userspace and kernalspace usage (20.4% + 5.1% = 25.5%).

**Comment by shiyanf** [comment]
@mattcolegate Thanks. Close this one.
