### ISSUE TITLE
Node.js v11 support

### ISSUE THREAD

**Issue by yuecchen** [RuntimeTools/appmetrics#559]
appmetrics does not support to installed with Node.js v11.*, it failed to be compiled.
environment information: redhat 7.4, node.js v11.3.0, gcc 4.8.5

Install Logs: 
[2018-11-28T14_57_12_372Z-debug.log](https://github.com/RuntimeTools/appmetrics/files/2625126/2018-11-28T14_57_12_372Z-debug.log)

**Comment by rwalle61** [comment]
As you closed https://github.com/RuntimeTools/appmetrics/issues/573, I assume this is safe to close too
