### ISSUE TITLE
npm appmetrics issue - again

### ISSUE THREAD

**Issue by Pigmalion** [RuntimeTools/appmetrics#569]
Hi ,
getting this error again on **npm i appmetrics**
even after deleting node_modules lib and clearing npm cache by force. 

_gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@4.0.1 install: `node extract_all_binaries.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appmetrics@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above._

Thanks.

**Comment by matth-c3** [comment]
Hello same for me, on Mac. mojave 10.14.3
npm version 6.7.0 
python 2 et 3, meme resultat.

**Comment by mattcolegate** [comment]
Hi @Pigmalion , @matth-c3 ,
Can you please post the entirety of the console output you get after executing `npm i appmetrics`?

**Comment by yasir-rafiq** [comment]
getting same error as above.

**Comment by mattcolegate** [comment]
Hi @yasir-rafiq,
Can you please post the entirety of the console output you get after executing npm i appmetrics?

**Comment by mattcolegate** [comment]
Closing this issue as not getting a response from OP - please will you all try again with the latest appmetrics (5.0.5) and raise a new issue if there continues to be a problem?
