### ISSUE TITLE
Prebuilts for Node v10 and Node v12

### ISSUE THREAD

**Issue by Just-Sieb** [RuntimeTools/appmetrics#584]
I have noticed that version 4.0.1 has the prebuilts of the native node module available for Node v8 so it does not have to compile during the install step. Can you start adding prebuilts for v10 and v12 of NodeJS as well?

**Comment by mattcolegate** [comment]
I'm afraid not - we no longer have the infrastructure available to continue supplying pre-built binaries. You will have to ensure that you have the pre-requisites installed on your machine to enable binary compilation, as described at https://github.com/RuntimeTools/appmetrics#pre-requisites
