### ISSUE TITLE
npm install fails on z/OS

### ISSUE THREAD

**Issue by matthewpwilson** [RuntimeTools/appmetrics#604]
```
> appmetrics@5.0.3 install /u/wilson/node/appmetrics-again/node_modules/appmetrics
> node showBuildInfo.js && node-gyp rebuild

path.js:1165
        path = process.cwd();
                       ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1165:24)
    at startup (bootstrap_node.js:185:32)
    at bootstrap_node.js:625:3
```
Using Node 8.16. 
I'll attach the full log.

**Comment by matthewpwilson** [comment]
[npm-debug-appmetrics.log](https://github.com/RuntimeTools/appmetrics/files/3451233/npm-debug-appmetrics.log)

**Comment by mattcolegate** [comment]
Process.cwd() is a base Node.js function - https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_cwd
What happens if you run `console.log('Current directory: ${process.cwd()}');`
If you get the same error, then the problem is likely with base Node.js rather than Appmetrics.

**Comment by mattcolegate** [comment]
A cursory google for 'process.swd no such file or directory' turns up a few instances where this happens when a Node application is running in a directory that has just been deleted by another terminal session. This can be checked by exiting the application, changing directory to root and back again.

**Comment by mattcolegate** [comment]
@matthewpwilson Are you still experiencing this issue?

**Comment by matthewpwilson** [comment]
Yes, but it does appear to be a general problem with npm/node-gyp on my system :-(
