### ISSUE TITLE
Install fails on Node 12 on Windows

### ISSUE THREAD

**Issue by connorjburton** [RuntimeTools/appmetrics#608]
Hi,

See the log below, failing to install on Windows Node 12.10.0

[ConEmu-2019-09-06-p2052.txt](https://github.com/RuntimeTools/appmetrics/files/3583420/ConEmu-2019-09-06-p2052.txt)

**Comment by mattcolegate** [comment]
Can't reproduce using my Windows 10 machine with Node 12.10.0 installing appmetrics latest (5.0.3) from npm. I notice the errors you're getting in that log are all for files in `c:\\node_modules\nan` - it might be worth clearing that directory out and letting npm download a fresh version?

**Comment by connorjburton** [comment]
After uninstalling and installing again the issue has resolved itself. Recently switched to `nvm` for node version management which may have been the catalyst.

Will close this and thanks for the super quick response!
