### ISSUE TITLE
Add support for MQLight monitoring

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics#64]
I'd like to add support for the MQLight npm module.

The data produced would be:

# Event: 'mqlight'

Emitted when a MQLight message is sent or received.

* `data` (Object) the data from the MQLight event: 
 * `time` (Number) the time in milliseconds when the MQLight event occurred. This can be converted to a Date using new Date(data.time)
 * `clientid` (String) the id of the client
 * `data` (String) the data sent if a 'send' or 'message', undefined for other calls.  Truncated if longer than 25 characters.
 * `method` (String) the name of the call or event (will be one of 'send' or 'message')
 * `topic` (String) the topic on which a message is sent/received
 * `qos` (Number) the QoS level for a 'send' call, undefined if not set
 * `duration` (Number) the time taken in milliseconds.

**Comment by seabaylea** [comment]
@sjanuary What's the approach for tuncating messages? Do we just cut off at 25 characters? (ie, is there a way to know its truncated rather than just happens to be 25 characters?)

**Comment by sjanuary** [comment]
If the message length is greater than 25 characters then it is truncated to 22 characters and an ellipsis ("...") is appended to show that it has been truncated.
