### ISSUE TITLE
Add support for LevelDOWN monitoring

### ISSUE THREAD

**Issue by aaroncollins** [RuntimeTools/appmetrics#67]
I'd like to add support for the LevelDOWN npm module. 

# Iterator 
Currently, the probe can monitor calls to *put()*, *get()*, *del()* and *batch()*. An iterator object can be made using [Leveldown.iterator](https://www.npmjs.com/package/leveldown#leveldown_iterator) which can query the database using *next()* and *seek()*, so support for these calls should be considered.

The current implementation of `aspectLvldownMethod()` only supports methods which require a callback to be passed as an argument. *Iterator.seek()* doesn't require a callback as an argument and so this implementation will need to be changed to cater to this

# aspect.afterConstructor()
Currently the implementation of `prototype.attach()` wraps the `leveldown` target in a new function as it uses a constructor. The `afterConstructor()` function has been added to the `aspect` API which replicates this, so it'd be best to change the implementation of `attach()` to use `afterConstructor()`

The prototype can be found in [my fork of appmetrics](https://github.com/aaroncollins/appmetrics/tree/leveldown-probe)

#  ~~Emitting arguments~~
~~The data emitted by the probe's implementation of *metricsEnd()* currently emits:~~
~~- Time of the call~~
~~- the method being called~~
~~- the duration of the call~~

~~This should also emit the methodArgs variable in some form~~

**Comment by aaroncollins** [comment]
I'm currently working on emitting method args

**Comment by aaroncollins** [comment]
The arguments are now being emitted for the leveldown methods below:
- *put()* emits both key and value being put into database (`reponse.key` and `response.value`)
- *get()* and *del()* emits the key being retrieved/used for deletion (`response.key`)
- *batch()* emits the number of operations being carried out by the batch (`response.opCount`)

**Comment by seabaylea** [comment]
Closing based on PR #98
