### ISSUE TITLE
Add support for Redis monitoring

### ISSUE THREAD

**Issue by hhellyeribm** [RuntimeTools/appmetrics#68]
Add appmetrics probe support for the redis npm module.

The data produced would be:

# Event: 'redis'

Emitted when a Redis client sends commands to a Redis server emit a 'redis' event and create a request.

## Event:
* __data__ (Object) the data from the redis event:
  * __time__ (Number) the time in milliseconds when the Redis event occurred. This can be converted to a Date using new Date(data.time)
  * __args__ (Array) A truncated version of the arguments to the Redis command. No more than 10 arguments are returned and string arguments are truncated. Callbacks are not included in the arguments.
  * __cmd__ (String) the Redis command sent to the server or 'batch.exec'/'multi.exec' for groups of command sent using batch/multi calls.
  * __duration__ (Number) the time taken in milliseconds.

## Request:
* __type: 'redis'__ - a request with type: 'redis' is started when a call is made to Redis.
* __root request: false__ - Redis requests are started by the running nodejs program not triggered by external events so they are children of a request triggered from outside.
* __context__ - the context object will contain:
  * __cmd (String)__ the Redis command sent to the server or 'batch.exec'/'multi.exec' for groups of command sent using batch/multi calls.
  * __args:  (Array)__ A truncated version of the arguments to the Redis command. No more than 10 arguments are returned and string arguments are truncated. Callbacks are not included in the arguments.

## Testcase:

* Connect to redis server and runs several basic commands.
* Create batch and multi objects and runs those.
* Create a publisher and subscriber test.
* Count the correct number of events have been received and that call backs passed to those calls were run correctly.

**Comment by seabaylea** [comment]
Closding based on PR#79
