### ISSUE TITLE
Add event loop latency data

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#72]
It is interesting to understand how long the period is between requesting a task run on the event loop and it beginning execution.

This can be tracked by periodically:

* taking a timestamp
* enqueuing a callback that emits a monitoring event containing the time elapsed since the timestamp

The callback could be enqueued by, for example: `process.nextTick()`, `setImmediate()`, `setTimeout()` or event at the native layer with `uv_async_send()`.

**Comment by tunniclm** [comment]
NOTE:

Ideally we would pull this metric from the libuv directly, but I don't think you can calculate it without a hook that allows you to discover when the event loop is idle versus when it is actively running callbacks.

**Comment by seabaylea** [comment]
Below is the proposed event schema for the event loop latency monitoring:

### Event: 'eventloop'
Emitted every 5 seconds, summarising sample based information of the event loop latency
* `data` (Object) the data from the event loop sample:
    * `time` (Number) the milliseconds when the event was emitted. This can be converted to a Date using `new Date(data.time)`.
    * `latency.min` (Number) the shortest sampled latency, in milliseconds.
    * `latency.max` (Number) the longest sampled latency, in milliseconds.
    * `latency.avg` (Number) the average sampled latency, in milliseconds.

**Comment by seabaylea** [comment]
Closing based on PR #100
