### ISSUE TITLE
Add io.js support

### ISSUE THREAD

**Issue by wyaeld** [RuntimeTools/appmetrics#8]
Since much of the community has moved over to io.js, does this project work on it?

**Comment by zeitiger** [comment]
:+1:

**Comment by tunniclm** [comment]
Right now appmetrics won't install on io.js but it's definitely something I want to get working very soon.

**Comment by jasnell** [comment]
@tunniclm ... let me know if there's anything in particular you need to help get that going. The new Node.js TLS release that we're working towards right now is targeted for early October. It will essentially be io.js + v0.12 so we'll want to make sure appmetrics is updated to support it.

**Comment by seabaylea** [comment]
At the moment a pre-built module binary is downloaded at install time, and those are currently available for Node.js 0.10 and 0.12.

With the uplift of the NODE_MODULE_VERSION between Node.js 0.12 and io.js, some additional pre-built binaries will be required for io.js. There were module version changes at 1.0.x, 1.1.x and 2.x so we might support all of those, or just the 2.x line if that's reasonable.

**Comment by tunniclm** [comment]
I managed to get something compiled and starting today on the latest io.js version. It's not running perfectly yet due to some behaviour changes related to the V8 APIs -- a missing `HandleScope` that wasn't problematic for the version on V8 in Node 0.10 or 0.12.

**Comment by tunniclm** [comment]
Once we have completed #11 it should be possible to compile from source against io.js for any version that is supported by nan@1.8.4 (I have tested io.js v2.3 and v2.5).

**Comment by tunniclm** [comment]
Version 1.0.1 provides support for io.js v2.5 and that is documented in the updated README.md.
Since io.js v3 has been released we now need to look at what needs to be done to bring us up to date.
