### ISSUE TITLE
Profiling fields not correctly escaped for CSV 

### ISSUE THREAD

**Issue by tunniclm** [RuntimeTools/appmetrics#83]
The profiling plugin does not correctly escape method names (and probably script resource names) for CSV. These need to double-quote strings containing commas or double-quotes (and also backslash escape double-quotes in the value).

Example of problematic message content:

```
NodeProfData,Start,1448976339186
...
NodeProfData,Node,238,233,,RegExp: [,]+,0,1
...
NodeProfData,End
```

This affects both HealthCenter (MQTT) which send malformed CSV, and the event API which reports incorrect values for method, line number and sample count (eg: for the above, the method name would be "RegExp: [", the line number would be "]+" and sample count "0".)

**Comment by tobespc** [comment]
we can now output the profiling data in json format, if we make this the default, we could add a fix to Health Center to parse the data from json rather than the current string

**Comment by tobespc** [comment]
closing as data can be output in json and we are not going to modify HC.  appmetrics-dash is the method for visualising data from appmetrics and this is where any further development on profiling will go
