### ISSUE TITLE
MQLight monitoring should start a request for incoming messages

### ISSUE THREAD

**Issue by seabaylea** [RuntimeTools/appmetrics#85]
@sjanuary I should have picked this up during the PR review. In the following:
https://github.com/RuntimeTools/appmetrics/blob/master/probes/mqlight-probe.js#L130

the request is always set to being a root (ie, the start of a new request). That should only apply to messages received on a subscribed topic - outbound published messages may form part of a request but won't be the start of one.

Can you add a check for the method type and set true/false as appropriate?

**Comment by sjanuary** [comment]
Yes, I will take a look.  So a 'publish' method will be root, but otherwise false.

**Comment by seabaylea** [comment]
The desired behaviour is the reverse - an incoming `message` event can drive the application to do work, and therefore should be a request root, whereas an outgoing `publish` is likely to occur as a result of other work in the system, so should be an event in an existing request.

**Comment by sjanuary** [comment]
Ok, I think I understand the idea now.

Committed the fix to my mqlight branch:

https://github.com/sjanuary/appmetrics/commit/71cc4d7d99b58dc079a056530366735952a86601

**Comment by seabaylea** [comment]
That looks good. Can you open a PR?

**Comment by sjanuary** [comment]
Done, #88

**Comment by seabaylea** [comment]
Fixed by #88
